// Storage landing workspace. Existing management views remain reachable.
const swBytes=n=>Number.isFinite(Number(n))&&n!==null?(Number(n)>=1099511627776?(Number(n)/1099511627776).toFixed(2)+' TiB':(Number(n)/1073741824).toFixed(1)+' GiB'):'—';
const swGB=n=>Number.isFinite(Number(n))&&n!==null?(Number(n)>=1000?(Number(n)/1000).toFixed(2)+' TB':Number(n).toFixed(1)+' GB'):'—';
const swTone=s=>['ok','online','passed'].includes(String(s).toLowerCase())?'ok':['warn','degraded','failed','faulted','offline'].includes(String(s).toLowerCase())?'warn':'unknown';
function swDiskForSlot(slot,disks){
 const device=(slot?.device||slot?.bay||'').replace(/^\/dev\//,'');
 if(device){const exact=disks.find(d=>d.bay===device);if(exact&&(!slot.serial||slot.serial==='—'||slot.serial===exact.serial))return exact}
 if(slot?.serial&&slot.serial!=='—'){const found=disks.filter(d=>d.serial===slot.serial);if(found.length===1)return found[0]}
 return null;
}
const swRequest=async(path,signal)=>{
 const ctrl=new AbortController(),abort=()=>ctrl.abort();if(signal?.aborted)abort();else signal?.addEventListener('abort',abort,{once:true});
 const timer=setTimeout(abort,20000);
 try{const r=await fetch(path,{credentials:'include',signal:ctrl.signal});const d=await r.json();if(!r.ok||d.error)throw Error(d.error||'Błąd odczytu');return d}
 catch(e){if(ctrl.signal.aborted&&!signal?.aborted)throw Error('Brak odpowiedzi przez 20 sekund');throw e}
 finally{clearTimeout(timer);signal?.removeEventListener('abort',abort)}
};
function StorageWorkspace({onNavigate,onDisk,onPool,onCreate,onMount,onFstab,onFormat,selected}){
 const disks=window.useStore('DISKS')||[];
 const [pools,setPools]=React.useState([]),[mounts,setMounts]=React.useState([]),[enclosure,setEnclosure]=React.useState(null),[jobs,setJobs]=React.useState([]),[errors,setErrors]=React.useState({}),[loaded,setLoaded]=React.useState(false),[bayBusy,setBayBusy]=React.useState(false),[query,setQuery]=React.useState('');
 const load=React.useCallback(async(signal)=>{
  const sources=[['pools','/api/storage/pools'],['mounts','/api/storage/mounts'],['jobs','/api/storage/jobs']];
  await Promise.all(sources.map(async([key,path])=>{try{const d=await swRequest(path,signal);if(signal.aborted)return;if(key==='pools')setPools(Array.isArray(d)?d:d.pools||[]);if(key==='mounts')setMounts(Array.isArray(d)?d:[]);if(key==='jobs')setJobs(d.jobs||[]);setErrors(e=>({...e,[key]:''}))}catch(e){if(!signal.aborted)setErrors(prev=>({...prev,[key]:e.message}))}}));if(!signal.aborted)setLoaded(true);
 },[]);
 const loadBays=React.useCallback(async(signal)=>{setBayBusy(true);const ctrl=new AbortController();const abort=()=>ctrl.abort();signal?.addEventListener('abort',abort,{once:true});const timer=setTimeout(abort,20000);try{const d=await swRequest('/api/bays',ctrl.signal);if(!signal?.aborted){setEnclosure(d);setErrors(e=>({...e,bays:''}))}}catch(e){if(!signal?.aborted)setErrors(prev=>({...prev,bays:e.name==='AbortError'?'Przekroczono czas odczytu zatok':e.message}))}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);if(!signal?.aborted)setBayBusy(false)}},[]);
 React.useEffect(()=>{const ctrl=new AbortController();let timer;const refresh=async()=>{await load(ctrl.signal);if(!ctrl.signal.aborted)timer=setTimeout(refresh,30000)};refresh();loadBays(ctrl.signal);const changed=()=>load(ctrl.signal);window.addEventListener('nimbus-storage-changed',changed);window.addEventListener('nimbus-storage-job',changed);return()=>{ctrl.abort();clearTimeout(timer);window.removeEventListener('nimbus-storage-changed',changed);window.removeEventListener('nimbus-storage-job',changed)}},[load,loadBays]);
 const zfs=pools.filter(p=>p.kind!=='mount'),dataMounts=pools.filter(p=>p.kind==='mount');
 const chosen=disks.find(d=>d.bay===(selected?.bay||selected))||disks[0]||null;
 const slots=enclosure?.slots||[],count=Math.max(25,Number(enclosure?.enclosure?.total_slots)||0,...slots.map(s=>Number(s.slot)||0));
 const mapped=slots.some(s=>s.pd_id);
 const list=disks.filter(d=>[d.bay,d.model,d.serial,d.pool].join(' ').toLowerCase().includes(query.toLowerCase()));
 const working=jobs.filter(j=>['queued','running'].includes(j.state)),failed=jobs.filter(j=>['failed','interrupted'].includes(j.state)||j.result?.error);
 const selectPool=p=>onPool({...p,id:p.id||p.name,total:p.total||0,used:p.used||0,avail:p.avail,health:swTone(p.health)});
 return <div className="sw-workspace">
  <header className="sw-heading"><div><span className="sw-eyebrow">MAGAZYN DANYCH</span><h2>Dyski i pule</h2></div><div className="sw-actions"><button className="btn" onClick={onFstab}>FSTAB</button><button className="btn" onClick={onMount}>Zamontuj dysk</button><button className="btn primary" onClick={onCreate}><window.Icon name="plus" size={15}/> Utwórz pulę</button></div></header>
  <div className="sw-stats">{[['Dyski',disks.length,'Wykryte urządzenia'],['Pule ZFS',loaded?zfs.length:'—','Zarządzanie pulami i danymi'],['Montowania danych',loaded?dataMounts.length:'—','Widoczne także montowane ręcznie'],['Zadania',loaded?working.length:'—',failed.length?failed.length+' wymaga sprawdzenia':'W kolejce i w toku']].map(([title,value,sub])=><button key={title} className="sw-stat" onClick={()=>onNavigate(title==='Dyski'?'disks':title==='Zadania'?'jobs':title==='Pule ZFS'?'pools':'mounts')}><span>{title}</span><strong>{value}</strong><small>{sub}</small></button>)}</div>
  {Object.entries(errors).filter(([,e])=>e).map(([key,error])=><div key={key} className="storage-alert" role="alert">{{bays:'Zatoki',pools:'Pule',mounts:'Montowania',jobs:'Zadania'}[key]}: {error}</div>)}
  <div className="sw-columns"><main className="sw-main">
   <section className="sw-panel sw-enclosure"><div className="sw-section-head"><div><h3>HP ProLiant <span className="sw-subtle">· 2U</span></h3><p>{enclosure?.enclosure?.name||'Mapa zatok'} · {mapped?'mapowanie z kontrolera':'schemat — brak potwierdzonego mapowania'}</p></div><button className="btn sm" disabled={bayBusy} onClick={()=>loadBays()}>{bayBusy?'Odczyt…':'Odśwież zatoki'}</button></div>
    <div className="sw-bay-grid" aria-label="Mapa zatok serwera">{Array.from({length:Math.min(count,100)},(_,i)=>{const slot=mapped?slots.find(s=>Number(s.slot)===i+1):null;const d=slot?swDiskForSlot(slot,disks):null;const tone=slot?.occupied?swTone(d?.smart||slot.smart):'unknown';return <button key={i} className={'sw-bay '+(slot?.occupied?'occupied ':'')+tone+(d&&chosen?.bay===d.bay?' selected':'')} disabled={!d} onClick={()=>onDisk(d)} aria-label={'Zatoka '+(i+1)+': '+(d?.bay||(slot?slot.occupied?'dysk bez mapowania':'pusta':'brak danych'))} aria-pressed={!!d&&chosen?.bay===d.bay}><span className="sw-bay-number">{String(i+1).padStart(2,'0')}</span><span className="sw-bay-drive">{d?.bay||(slot?slot.occupied?'Dysk':'Pusta':'—')}</span><span className="sw-bay-size">{d?.size||slot?.size||''}</span><i className={'sw-bay-led '+(slot?.occupied?'lit':'')} aria-hidden="true"/></button>})}</div>
    <div className="sw-legend"><span><i className="sw-indicator ok"/> Dysk obecny</span><span><i className="sw-indicator warn"/> Wymaga uwagi</span><span><i className="sw-indicator"/> Pusta / brak danych</span><button onClick={()=>onNavigate('leds')}>Identyfikacja LED →</button></div>
   </section>
   <section className="sw-panel"><div className="sw-section-head"><div><h3>Pule ZFS</h3><p>Pojemność, stan i organizacja danych</p></div><button className="btn sm" onClick={()=>onNavigate('pools')}>Zarządzaj pulami</button></div><div className="sw-pools">{zfs.map((p,i)=>{const pct=p.total>0?Math.max(0,Math.min(100,p.used/p.total*100)):0;const tone=swTone(p.health);return <button className={'sw-pool sw-color-'+i%3} key={p.id||p.name} onClick={()=>selectPool(p)}><div className="sw-pool-title"><span className="sw-pool-symbol"><window.Icon name="disk" size={23}/></span><div><strong>{p.name}</strong><small>{p.type||'ZFS'} · {p.drives??'—'} dysków</small></div><span className={'sw-health '+tone}>{tone==='ok'?'ONLINE':p.health||'Brak odczytu'}</span></div><div className="sw-capacity"><strong>{swGB(p.used)}</strong><span>/ {swGB(p.total)}</span></div><div className="sw-capacity-bar"><i style={{width:pct+'%'}}/></div><div className="sw-pool-foot"><span>{swGB(p.avail??Math.max(0,(p.total||0)-(p.used||0)))} dostępne</span><b>{p.total>0?pct.toFixed(0)+'%':'—'}</b></div><div className="sw-pool-links">Szczegóły · Scrub · Migawki <span>→</span></div></button>})}{!zfs.length&&<div className="sw-empty">{loaded?'Brak pul ZFS. Utwórz pulę, aby rozpocząć.':'Ładowanie pul…'}</div>}</div></section>
   <section className="sw-panel"><div className="sw-section-head"><div><h3>Montowania danych</h3><p>Punkty montowania i start po restarcie</p></div><button className="btn sm" onClick={()=>onNavigate('mounts')}>Wszystkie montowania</button></div>{dataMounts.map(p=>{const m=mounts.find(m=>m.mount===p.mount);return <button className="sw-mount" key={p.id||p.mount} onClick={()=>onNavigate('mounts')}><span className="sw-pool-symbol"><window.Icon name="folder" size={20}/></span><span><strong>{p.mount||p.name}</strong><small>{p.device} · {p.type}</small></span><span className="sw-mount-size">{swGB(p.used)} / {swGB(p.total)}</span><span className={'sw-tag '+(m?.in_fstab?'ok':'')}>{m?m.in_fstab?'FSTAB':'Ręcznie':'—'}</span></button>})}{!dataMounts.length&&<div className="sw-empty">{loaded?'Brak zamontowanych dysków danych':'Ładowanie montowań…'}</div>}</section>
   <section className="sw-panel"><div className="sw-section-head"><h3>Wszystkie dyski</h3><input className="sw-search" aria-label="Szukaj dysku" placeholder="Nazwa, model, numer seryjny…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="sw-disk-list">{list.map(d=><button key={d.bay} className={'sw-disk-row '+(chosen?.bay===d.bay?'selected':'')} onClick={()=>onDisk(d)}><span className={'sw-indicator '+swTone(d.smart)}/><strong>{d.bay}</strong><span>{d.model}<small>{d.pool&&d.pool!=='—'?'Pula '+d.pool:d.mount||'Bez przypisanej puli'}</small></span><b>{d.size}</b><span>{Number(d.temp)>0?d.temp+'°C':'—'}</span></button>)}{!list.length&&<div className="sw-empty">Brak pasujących dysków</div>}</div></section>
  </main><aside className="sw-sidebar"><StorageInspector key={chosen?.bay||'empty'} disk={chosen} onFull={()=>{onDisk(chosen);onNavigate('disks')}} onFormat={onFormat}/><section className="sw-panel sw-jobs"><div className="sw-section-head"><h3>Operacje</h3><button className="btn sm" onClick={()=>onNavigate('jobs')}>Historia</button></div><div className="sw-inside">{working.length?working.slice(0,3).map(j=><div className="sw-job" key={j.id}><span className="sw-health">{j.state==='running'?'W toku':'Oczekuje'}</span><strong>{j.target||j.operation}</strong><small>{j.stage||j.operation}</small></div>):<p className="sw-muted">{loaded?'Brak oczekujących operacji.':'Ładowanie zadań…'}</p>}{failed.length>0&&<button className="btn" onClick={()=>onNavigate('jobs')}>{failed.length} operacji wymaga sprawdzenia</button>}</div></section></aside></div>
 </div>;
}
function StorageInspector({disk,onFull,onFormat}){
 const [layout,setLayout]=React.useState(null),[error,setError]=React.useState(''),[tab,setTab]=React.useState('layout'),[loading,setLoading]=React.useState(false);
 const reload=React.useCallback(async(signal)=>{if(!disk)return;setLoading(true);try{const d=await swRequest('/api/storage/device-layout?device='+encodeURIComponent(disk.bay),signal);if(!signal?.aborted){setLayout(d.blockdevices?.[0]||null);setError('')}}catch(e){if(!signal?.aborted)setError(e.message)}finally{if(!signal?.aborted)setLoading(false)}},[disk?.bay]);
 React.useEffect(()=>{const ctrl=new AbortController();reload(ctrl.signal);const changed=()=>reload(ctrl.signal);window.addEventListener('nimbus-storage-changed',changed);return()=>{ctrl.abort();window.removeEventListener('nimbus-storage-changed',changed)}},[reload]);
 if(!disk)return <section className="sw-panel"><div className="sw-empty">Wybierz dysk, aby zobaczyć partycje i dostępne operacje.</div></section>;
 const parts=(layout?.children||[]).filter(n=>n.type==='part');
 return <section className="sw-panel sw-inspector"><div className="sw-section-head"><div><span className="sw-eyebrow">WYBRANY DYSK</span><h3>{disk.bay}</h3><p>{disk.model}</p></div><span className={'sw-health '+swTone(disk.smart)}>{swTone(disk.smart)==='ok'?'SMART OK':swTone(disk.smart)==='warn'?'UWAGA':'SMART —'}</span></div><div className="sw-inside"><div className="sw-disk-size">{layout?swBytes(layout.size):disk.size}</div><p className="sw-muted">{disk.type} · {Number(disk.temp)>0?disk.temp+'°C':'Temperatura —'}</p><div className="sw-fact"><span>Numer seryjny</span><b>{disk.serial||'—'}</b></div><div className="sw-fact"><span>Pula</span><b>{disk.pool||'—'}</b></div></div><div className="sw-inspector-tabs">{[['layout','Partycje'],['plan','Plan zmian']].map(([key,title])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{title}</button>)}</div>{error&&<div className="storage-alert" role="alert">{error}</div>}
  <div hidden={tab!=='layout'} className="sw-inside">{loading&&!layout?<p className="sw-muted">Odczyt partycji…</p>:layout?<><div className="sw-partition-bar" aria-label="Udział rozmiarów partycji w pojemności dysku">{(parts.length?parts:[layout]).map((p,i)=><span key={p.name} className={'sw-color-'+i%3} style={{width:Math.min(100,Math.max(0,Number(p.size)/Number(layout.size)*100))+'%'}} title={(p.path||p.name)+' · '+swBytes(p.size)}/>)}</div><p className="sw-muted">Proporcje rozmiarów, bez odwzorowania sektorów.</p>{(parts.length?parts:[layout]).map((p,i)=><div className="sw-partition" key={p.name}><span className={'sw-part-key sw-color-'+i%3}/><div><strong>{p.name}</strong><small>{p.fstype||'Brak systemu plików'} · {p.mountpoint||'Niezamontowane'}</small></div><b>{swBytes(p.size)}</b></div>)}<button className="btn primary" style={{marginTop:18,width:'100%'}} onClick={()=>setTab('plan')}>Zarządzaj partycjami</button></>:<p className="sw-muted">Brak układu dysku.</p>}<div className="sw-actions" style={{marginTop:12}}><button className="btn" onClick={onFull}>SMART i montowania</button><button className="btn" onClick={()=>onFormat(disk)}>Formatowanie…</button></div></div>
  <div hidden={tab!=='plan'} className="sw-plan"><window.StoragePartitionPlan device={'/dev/'+disk.bay} onChanged={()=>reload()}/></div>
 </section>;
}
window.StorageWorkspace=StorageWorkspace;
window.StorageWorkspaceHelpers={swDiskForSlot,swTone};
