// ===== Dostęp zdalny: Tailscale + Cloudflare Tunnel =====
const RemoteAccess = () => {
  const [state,setState]=React.useState(null),[busy,setBusy]=React.useState(''),[message,setMessage]=React.useState(''),[token,setToken]=React.useState('');
  const load=()=>fetch('/api/remote-access/status',{credentials:'include'}).then(r=>r.json()).then(setState).catch(()=>{});
  React.useEffect(()=>{load();const t=setInterval(load,8000);return()=>clearInterval(t)},[]);
  const act=async(provider,action,extra={})=>{setBusy(provider+action);setMessage('');try{const r=await fetch('/api/remote-access/action',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,action,...extra})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Operacja nie powiodła się');setMessage(d.output||'Operacja zakończona');setTimeout(load,900)}catch(e){setMessage(e.message)}finally{setBusy('')}};
  if(!state)return <div className="card" style={{padding:40,textAlign:'center'}}>Sprawdzanie połączeń…</div>;
  const ts=state.tailscale||{},cf=state.cloudflare||{};
  const tsSelf=ts.details?.Self||{}, tsIPs=tsSelf.TailscaleIPs||[];
  const ServiceState=({data})=><span className={`badge ${data.running?'ok':data.installed?'warn':''}`}><span className={`dot ${data.running?'pulse':''}`}/>{data.running?'POŁĄCZONO':data.installed?'ZATRZYMANO':'NIEZAINSTALOWANE'}</span>;
  return <div className="col" style={{gap:'var(--gutter)'}}>
    <div className="card" style={{padding:20,background:'linear-gradient(120deg,color-mix(in oklch,var(--accent) 12%,var(--surface)),var(--surface))'}}><div className="row" style={{justifyContent:'space-between',alignItems:'flex-start'}}><div><div style={{fontSize:22,fontWeight:750}}>Bezpieczny dostęp z każdego miejsca</div><div className="card-sub" style={{marginTop:6,maxWidth:680}}>Połącz Nimbus i jego usługi bez przekierowania portów na routerze. Tailscale daje prywatną sieć urządzeń, a Cloudflare Tunnel publikuje wybrane aplikacje przez HTTPS.</div></div><Icon name="shield" size={30}/></div></div>
    {message&&<div className="card" style={{padding:12,color:message.toLowerCase().includes('błąd')?'var(--err)':'var(--fg-muted)',whiteSpace:'pre-wrap'}}>{message}</div>}
    <div className="grid grid-2">
      <div className="card" style={{padding:20}}><div className="row" style={{justifyContent:'space-between'}}><div className="row"><div style={{width:42,height:42,borderRadius:12,display:'grid',placeItems:'center',background:'var(--fg)',color:'var(--bg)',fontWeight:900}}>TS</div><div><div className="card-title">Tailscale</div><div className="card-sub">Prywatna sieć WireGuard mesh</div></div></div><ServiceState data={ts}/></div>
        <div className="grid grid-2" style={{marginTop:18}}><div className="kpi"><div className="kpi-label">ADRES TAILSCALE</div><div className="mono" style={{marginTop:8,fontWeight:700}}>{tsIPs[0]||'—'}</div></div><div className="kpi"><div className="kpi-label">NAZWA W SIECI</div><div className="mono" style={{marginTop:8,fontWeight:700}}>{tsSelf.DNSName||tsSelf.HostName||'—'}</div></div></div>
        <div className="row gap-sm" style={{marginTop:18,flexWrap:'wrap'}}>{!ts.installed&&<button className="btn primary" disabled={!!busy} onClick={()=>act('tailscale','install')}>Zainstaluj</button>}{ts.installed&&!ts.running&&<button className="btn" disabled={!!busy} onClick={()=>act('tailscale','start')}>Uruchom usługę</button>}{ts.installed&&<button className="btn primary" disabled={!!busy} onClick={()=>act('tailscale','connect')}>{ts.running?'Odśwież logowanie':'Połącz konto'}</button>}{ts.running&&<button className="btn" disabled={!!busy} onClick={()=>act('tailscale','logout')}>Wyloguj</button>}</div>
        <div className="card-sub" style={{marginTop:14}}>Po kliknięciu „Połącz konto” skopiuj wyświetlony adres logowania do przeglądarki. Porty NAS pozostają niewidoczne z publicznego internetu.</div>
      </div>
      <div className="card" style={{padding:20}}><div className="row" style={{justifyContent:'space-between'}}><div className="row"><div style={{width:42,height:42,borderRadius:12,display:'grid',placeItems:'center',background:'oklch(0.7 0.17 55)',color:'#151515',fontWeight:900}}>CF</div><div><div className="card-title">Cloudflare Tunnel</div><div className="card-sub">Publiczny HTTPS bez otwierania portów</div></div></div><ServiceState data={cf}/></div>
        <label style={{display:'block',marginTop:20}}>Token tunelu<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="eyJhIjoi…" autoComplete="off"/></label>
        <div className="row gap-sm" style={{marginTop:14,flexWrap:'wrap'}}>{!cf.installed&&<button className="btn" disabled={!!busy} onClick={()=>act('cloudflare','install')}>Zainstaluj cloudflared</button>}<button className="btn primary" disabled={!!busy||!token.trim()} onClick={()=>act('cloudflare','connect',{token})}>Podłącz tunel</button>{cf.installed&&!cf.running&&<button className="btn" disabled={!!busy} onClick={()=>act('cloudflare','start')}>Uruchom</button>}{cf.running&&<button className="btn" disabled={!!busy} onClick={()=>act('cloudflare','stop')}>Zatrzymaj</button>}</div>
        <div className="card-sub" style={{marginTop:14}}>Token pobierzesz w Cloudflare Zero Trust → Networks → Tunnels. Nimbus nie zapisuje go we własnej konfiguracji; przekazuje go instalatorowi usługi cloudflared.</div>
      </div>
    </div>
    <div className="card"><div style={{padding:16,borderBottom:'1px solid var(--line)'}}><div className="card-title">Co wybrać?</div></div><table className="table"><thead><tr><th>Potrzeba</th><th>Najlepsza opcja</th><th>Dlaczego</th></tr></thead><tbody><tr><td>Panel NAS, SSH, SMB i całe VLAN-y</td><td><span className="badge ok">Tailscale</span></td><td>Prywatny dostęp tylko dla Twoich urządzeń</td></tr><tr><td>Jellyfin, panel WWW lub aplikacja przez domenę</td><td><span className="badge warn">Cloudflare Tunnel</span></td><td>HTTPS i kontrola dostępu bez publicznego IP</td></tr><tr><td>Awaryjny dostęp administracyjny</td><td><span className="badge ok">Oba</span></td><td>Tailscale jako wejście techniczne, Cloudflare dla usług WWW</td></tr></tbody></table></div>
  </div>
};
window.RemoteAccess=RemoteAccess;
