// ===== IPMI / Czujniki — konsola sprzętowa HP/iLO =====
const IPMISparkline = window.Sparkline;
const IPMILineChart = window.LineChart;
const ipmiColors = {ok:'var(--ok)',warn:'var(--warn)',crit:'var(--err)',unknown:'var(--fg-dim)'};
const ipmiRank = {crit:0,warn:1,unknown:2,ok:3};

const ipmiIsFan=s=>s?.kind==='fan'||s?.unit==='RPM';
const ipmiHasValue=s=>!!s&&!s.unavailable&&!s.discrete&&Number.isFinite(Number(s.val));
const ipmiStatus = s => {
  if(!s)return 'unknown';
  const raw=(s.raw_status||'').toLowerCase();
  if(['cr','lcr','ucr','lnr','unr','critical','failure'].includes(raw))return 'crit';
  if(['nc','lnc','unc','non-critical'].includes(raw))return 'warn';
  if(!ipmiHasValue(s)||['ns','na','nr','unknown'].includes(raw))return 'unknown';
  if(ipmiIsFan(s))return Number(s.warn)>0&&Number(s.val)<Number(s.warn)?'warn':raw==='ok'?'ok':'unknown';
  if(s.unit==='°C')return Number(s.crit)>0&&Number(s.val)>=Number(s.crit)?'crit':Number(s.warn)>0&&Number(s.val)>=Number(s.warn)?'warn':'ok';
  return raw==='ok'?'ok':'unknown';
};
const ipmiValue = s => s?.discrete?`Stan: ${s.raw_value||s.raw_status||'nieznany'}`:!ipmiHasValue(s)?'Brak odczytu':`${Number(s.val).toLocaleString('pl',{maximumFractionDigits:2})} ${s.unit}`;

const IPMIStatusBadge=({status='unknown',text})=><span className={'badge '+(status==='crit'?'err':status==='warn'?'warn':status==='ok'?'ok':'')}><span className="dot"/>{text||(status==='crit'?'AWARIA':status==='warn'?'UWAGA':status==='ok'?'OK':'BRAK DANYCH')}</span>;
const IPMIThreshold=({s})=>ipmiIsFan(s)?<span>{s.warn?`minimum ${s.warn} ${s.unit}`:'Próg nieudostępniony przez BMC'}</span>:s.unit==='°C'?<span>uwaga {s.warn||'—'}°C · krytyczny {s.crit||'—'}°C</span>:<span>monitorowany przez BMC</span>;

const IPMIKPI=({icon,label,value,sub,status='ok',history})=><div className={'kpi ipmi-kpi '+status}>
  <div className="kpi-label"><Icon name={icon} size={13}/>{label}</div><div className="kpi-value" style={{color:ipmiColors[status]}}>{value}</div><div className="kpi-foot"><span>{sub}</span></div>
  {history&&history.length>1&&<IPMISparkline data={history} color={ipmiColors[status]}/>}
</div>;

const IPMIEmpty=({missing,onInstall,busy})=><div className="card ipmi-empty"><div className="ipmi-empty-icon"><Icon name={missing?'package':'cpu'} size={34}/></div><div className="card-title">{missing?'Brak narzędzi IPMI':'Nie wykryto kontrolera BMC/iLO'}</div><div className="card-sub">{missing?'Zainstaluj ipmitool, aby odczytywać telemetrię sprzętową, zasilanie i dziennik SEL.':'Kontroler nie odpowiedział w wyznaczonym czasie. Nimbus ponowi próbę bez blokowania pozostałych modułów.'}</div>{missing&&<button className="btn primary" disabled={busy} onClick={onInstall}>{busy?'Instalowanie…':'Zainstaluj ipmitool'}</button>}</div>;

const IPMIOverview=({I,g,history,onTab})=>{
  const tempHist=history.map(p=>p.temp).filter(v=>v>0),powerHist=history.map(p=>p.power).filter(v=>v>0),fanHist=history.map(p=>p.fan).filter(v=>v>0);
  const overall=g.alerts.some(a=>a.status==='crit')?'crit':g.alerts.length?'warn':'ok';
  return <div className="col" style={{gap:'var(--gutter)'}}>
    <div className="grid ipmi-kpi-grid">
      <IPMIKPI icon="shield" label="Stan sprzętu" value={overall==='crit'?'AWARIA':overall==='warn'?'UWAGA':'OK'} sub={g.alerts.length?`${g.alerts.length} aktywnych alarmów`:'Wszystkie odczyty prawidłowe'} status={overall}/>
      <IPMIKPI icon="thermometer" label="Najwyższa temperatura" value={g.hottest?`${g.hottest.val}°C`:'—'} sub={g.hottest?.name||`${g.temps.length} czujników`} status={g.hottest?ipmiStatus(g.hottest):'unknown'} history={tempHist}/>
      <IPMIKPI icon="fan" label="Wentylatory" value={`${g.fans.filter(f=>ipmiStatus(f)==='ok').length}/${g.fans.length}`} sub={g.fans.length?'Stan raportowany przez BMC':'Brak odczytu wentylatorów'} status={g.fans.some(f=>ipmiStatus(f)==='crit')?'crit':g.fans.some(f=>ipmiStatus(f)==='warn')?'warn':g.fans.length&&g.fans.every(f=>ipmiStatus(f)==='ok')?'ok':'unknown'} history={fanHist}/>
      <IPMIKPI icon="bolt" label="Pobór mocy" value={I.power?.totalW?`${I.power.totalW} W`:'—'} sub={I.power_meta?.redundancy||'DCMI'} history={powerHist}/>
      <IPMIKPI icon="hdd" label="Zasilacze" value={`${g.psuOK}/2`} sub={g.psuOK===2?'Redundancja aktywna':g.psuOK===1?'Brak redundancji':'Brak poprawnych odczytów'} status={g.psuOK===2?'ok':g.psuOK===1?'warn':'unknown'}/>
      <IPMIKPI icon="cpu" label="Połączenie iLO" value="ONLINE" sub={I.bmc?.ip||'Lokalny interfejs IPMI'}/>
    </div>
    <div className="grid grid-2-1">
      <div className="card"><div className="card-head"><div><div className="card-title">Telemetria serwera</div><div className="card-sub">Historia bieżącej sesji</div></div><button className="btn sm" onClick={()=>onTab('map')}>Mapa cieplna</button></div><div className="card-body ipmi-trends">
        <div><div className="ipmi-chart-label"><span>Temperatura maksymalna</span><b>{g.hottest?`${g.hottest.val}°C`:'—'}</b></div>{tempHist.length>1?<IPMILineChart series={[tempHist]} height={145} colors={['var(--warn)']}/>:<div className="ipmi-no-chart">Historia pojawi się po kolejnych odczytach</div>}</div>
        <div><div className="ipmi-chart-label"><span>Pobór mocy</span><b>{I.power?.totalW?`${I.power.totalW} W`:'—'}</b></div>{powerHist.length>1?<IPMILineChart series={[powerHist]} height={145} colors={['var(--accent)']}/>:<div className="ipmi-no-chart">DCMI nie zwróciło jeszcze historii</div>}</div>
      </div></div>
      <div className="card"><div className="card-head"><div><div className="card-title">Aktywne alarmy</div><div className="card-sub">Krytyczne wyświetlane pierwsze</div></div><span className={'badge '+(g.alerts.length?'warn':'ok')}>{g.alerts.length}</span></div><div className="card-body col" style={{gap:8}}>{!g.alerts.length&&<div className="ipmi-all-ok"><Icon name="check" size={24}/><b>Brak zgłoszonych alarmów</b><span>Sprawdź także czujniki bez odczytu i aktualność danych</span></div>}{g.alerts.slice(0,6).map((a,i)=><div className="ipmi-alert-row" key={i}><span className={'disk-led '+(a.status==='crit'?'warn':'')}/><div><b>{a.name}</b><span>{ipmiValue(a)}</span></div><IPMIStatusBadge status={a.status}/></div>)}{g.alerts.length>6&&<button className="btn sm" onClick={()=>onTab('sensors')}>Pokaż wszystkie</button>}</div></div>
    </div>
  </div>;
};

const zoneSensor=(sensors,words)=>{const m=sensors.filter(s=>s.unit==='°C'&&ipmiHasValue(s)&&words.some(w=>s.name.toLowerCase().includes(w)));return m.length?m.reduce((a,b)=>Number(a.val)>Number(b.val)?a:b):null;};
const IPMIHeatMap=({sensors})=>{
  const zones=[['drives','Backplane · 25 zatok',['drive','storage','hdd','backplane','disk'],'hdd'],['cpu1','Procesor 1',['cpu 1','cpu1','processor 1','proc 1'],'cpu'],['cpu2','Procesor 2',['cpu 2','cpu2','processor 2','proc 2'],'cpu'],['memory','Pamięć / DIMM',['dimm','memory','mem'],'ram'],['array','Smart Array / PCIe',['array','raid','pci','pch','controller'],'disk'],['air','Powietrze / płyta',['ambient','inlet','system','board','exhaust','outlet'],'fan']].map(([id,name,words,icon])=>({id,name,icon,s:zoneSensor(sensors,words)}));
  const temps=sensors.filter(s=>s.unit==='°C'&&ipmiHasValue(s)).sort((a,b)=>b.val-a.val);
  return <div className="grid grid-2-1"><div className="card"><div className="card-head"><div><div className="card-title">Mapa cieplna HP ProLiant</div><div className="card-sub">Schemat funkcjonalny · telemetria BMC</div></div><div className="ipmi-legend"><span className="ok">OK</span><span className="warn">UWAGA</span><span className="crit">KRYTYCZNY</span></div></div><div className="card-body"><div className="ipmi-chassis"><div className="ipmi-chassis-title"><span>HP PROLIANT · 2U</span><span className="mono">AIRFLOW →</span></div><div className="ipmi-chassis-grid">{zones.map(z=>{const st=z.s?ipmiStatus(z.s):'unknown';return <div key={z.id} className={`ipmi-zone ${z.id} ${st}`}><Icon name={z.icon} size={20}/><b>{z.name}</b><strong>{z.s?`${z.s.val}°C`:'—'}</strong><small>{z.s?.name||'Brak osobnego czujnika'}</small>{z.id==='drives'&&<div className="ipmi-bays">{Array.from({length:25},(_,i)=><i key={i}/>)}</div>}</div>})}<div className="ipmi-zone psu ok"><Icon name="bolt" size={20}/><b>Zasilacze redundantne</b><strong>PSU 1 + PSU 2</strong><small>Tylna część obudowy</small></div></div></div></div></div>
    <div className="card"><div className="card-head"><div><div className="card-title">Temperatury BMC</div><div className="card-sub">{temps.length} aktywnych odczytów</div></div></div><div className="card-body col" style={{gap:8}}>{temps.map((s,i)=>{const st=ipmiStatus(s),pct=Math.min(100,(s.val/(s.crit||100))*100);return <div className="ipmi-temp-row" key={i}><div><b>{s.name}</b><span><IPMIThreshold s={s}/></span></div><strong style={{color:ipmiColors[st]}}>{s.val}°C</strong><div className={'bar '+(st==='crit'?'err':st==='warn'?'warn':'ok')}><i style={{width:pct+'%'}}/></div></div>})}{!temps.length&&<div className="ipmi-no-chart">Brak czujników temperatury</div>}</div></div></div>;
};

const IPMISensors=({sensors})=>{
  const [type,setType]=React.useState('all'),[query,setQuery]=React.useState('');
  const types=[['all','Wszystkie'],['°C','Temperatura'],['fan','Wentylatory'],['V','Napięcia'],['W','Moc'],['A','Prąd']];
  const visible=sensors.filter(s=>(type==='all'||(type==='fan'?ipmiIsFan(s):s.unit===type))&&s.name.toLowerCase().includes(query.toLowerCase())).map(s=>({...s,status:ipmiStatus(s)})).sort((a,b)=>ipmiRank[a.status]-ipmiRank[b.status]||a.name.localeCompare(b.name));
  return <div className="card"><div className="card-head ipmi-sensor-head"><div><div className="card-title">Wszystkie czujniki</div><div className="card-sub">Alarmy zawsze wyświetlane na początku</div></div><div className="topbar-search ipmi-search"><Icon name="search" size={12}/><input placeholder="Szukaj czujnika…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="ipmi-filter-row">{types.map(([id,label])=><button key={id} className={'btn sm '+(type===id?'primary':'ghost')} onClick={()=>setType(id)}>{label}<span className="badge">{sensors.filter(s=>id==='all'||(id==='fan'?ipmiIsFan(s):s.unit===id)).length}</span></button>)}</div><div style={{overflow:'auto'}}><table className="table"><thead><tr><th>Stan</th><th>Czujnik</th><th>Typ</th><th>Wartość</th><th>Zakres / próg</th><th>Wykorzystanie progu</th></tr></thead><tbody>{visible.map((s,i)=>{const denom=s.unit==='RPM'?s.max:(s.crit||s.max),pct=denom>0&&ipmiHasValue(s)&&!s.discrete?Math.min(100,Math.max(0,Math.abs(s.val/denom)*100)):0;return <tr key={i}><td><IPMIStatusBadge status={s.status}/></td><td><b>{s.name}</b></td><td><span className="chip">{s.unit==='°C'?'Temperatura':ipmiIsFan(s)?'Wentylator':s.unit==='V'?'Napięcie':s.unit==='W'?'Moc':'Prąd'}</span></td><td className="mono" style={{color:ipmiColors[s.status],fontWeight:600}}>{ipmiValue(s)}</td><td className="mono dim"><IPMIThreshold s={s}/></td><td style={{minWidth:160}}>{denom>0&&ipmiHasValue(s)?<div className={'bar '+(s.status==='crit'?'err':s.status==='warn'?'warn':'ok')}><i style={{width:pct+'%'}}/></div>:<span className="dim">—</span>}</td></tr>})}{!visible.length&&<tr><td colSpan={6} className="dim" style={{textAlign:'center',padding:30}}>Brak czujników pasujących do filtra</td></tr>}</tbody></table></div></div>;
};

const IPMIPower=({I,history})=>{const h=history.map(p=>p.power).filter(v=>v>0),psus=[I.power?.psu1,I.power?.psu2];return <div className="col" style={{gap:'var(--gutter)'}}><div className="grid grid-3">{psus.map((psu,i)=>{const ok=psu?.status==='OK';return <div className={'card ipmi-psu '+(ok?'ok':'warn')} key={i}><div className="card-body"><div className="ipmi-psu-icon"><Icon name="bolt" size={24}/></div><div><span className="dim">ZASILACZ {i+1}</span><h3>{psu?.status||'—'}</h3><div className="mono dim">Wyjście: {psu?.out||'—'}</div></div><IPMIStatusBadge status={ok?'ok':psu?.status==='—'?'unknown':'warn'}/></div></div>})}<div className="card"><div className="card-body"><div className="ipmi-psu-icon accent"><Icon name="shield" size={24}/></div><div><span className="dim">REDUNDANCJA</span><h3>{I.power_meta?.redundancy||'—'}</h3><div className="mono dim">Stan systemu: {I.power?.state||'—'}</div></div></div></div></div><div className="card"><div className="card-head"><div><div className="card-title">Pobór mocy serwera</div><div className="card-sub">DCMI · historia bieżącej sesji</div></div><strong className="mono" style={{fontSize:22}}>{I.power?.totalW?`${I.power.totalW} W`:'—'}</strong></div><div className="card-body">{h.length>1?<IPMILineChart series={[h]} height={240} colors={['var(--accent)']}/>:<div className="ipmi-no-chart">Potrzebne są co najmniej dwa poprawne odczyty DCMI</div>}</div></div></div>};

const IPMISEL=({I,clearing,onClear})=>{const [sev,setSev]=React.useState('all'),events=(I.events||[]).filter(e=>sev==='all'||e.sev===sev);return <div className="card"><div className="card-head"><div><div className="card-title">Dziennik zdarzeń sprzętowych SEL</div><div className="card-sub">{I.sel_entries>=0?`${I.sel_entries} wpisów zgłoszonych przez BMC`:'Liczba wpisów niedostępna'} · cache 60 sekund</div></div><div className="card-actions"><div className="segmented">{['all','crit','warn','info'].map(v=><button key={v} className={sev===v?'active':''} onClick={()=>setSev(v)}>{v==='all'?'Wszystkie':v.toUpperCase()}</button>)}</div><button className="btn sm ghost" disabled={clearing} onClick={onClear}>{clearing?'Czyszczenie…':'Wyczyść SEL'}</button></div></div><div className="card-body flush">{!events.length&&!(I.sel_raw||[]).length&&<div className="ipmi-all-ok"><Icon name="check" size={24}/><b>Brak zdarzeń sprzętowych</b><span>Dziennik SEL jest pusty</span></div>}{events.map((e,i)=><div className="ipmi-event" key={i}><span className="mono dim">{e.t}</span><IPMIStatusBadge status={e.sev==='info'?'unknown':e.sev}/><div><b>{e.msg}</b><span>{e.src}</span></div></div>)}{!events.length&&(I.sel_raw||[]).map((line,i)=><div className="ipmi-event raw" key={i}><span className="mono">{line}</span></div>)}</div></div>};

const IPMIBMC=({I,onRefresh})=><div className="grid grid-2-1"><div className="card"><div className="card-head"><div><div className="card-title">Kontroler zarządzający iLO/BMC</div><div className="card-sub">{I.bmc?.model||'Kontroler IPMI'}</div></div><IPMIStatusBadge status="ok" text="POŁĄCZONO"/></div><div className="card-body ipmi-bmc-grid">{[['Adres IP',I.bmc?.ip],['Adres MAC',I.bmc?.mac],['Firmware',I.bmc?.fw],['Protokół','IPMI 2.0'],['Stan obudowy',I.chassis?.intrusion],['Panel przedni',I.chassis?.frontPanel]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v||'—'}</strong></div>)}</div><div className="card-body ipmi-bmc-actions">{I.bmc?.ip&&I.bmc.ip!=='—'&&<button className="btn primary" onClick={()=>window.open('https://'+I.bmc.ip,'_blank','noopener')}>Otwórz konsolę iLO</button>}<button className="btn" onClick={onRefresh}><Icon name="refresh" size={12}/> Odśwież dane statyczne</button></div></div><div className="card"><div className="card-head"><div><div className="card-title">Bezpieczne odpytywanie</div><div className="card-sub">Ochrona przed zawieszonym BMC</div></div></div><div className="card-body col" style={{gap:12}}>{[['3 / 15 sekund','limit polecenia / pełnej listy czujników'],['20 sekund','wspólny cache IPMI i temperatur'],['5 minut','cache danych LAN i firmware'],['60 sekund','cache dziennika SEL']].map(([v,l])=><div className="ipmi-policy" key={v}><b>{v}</b><span>{l}</span></div>)}</div></div></div>;

const IPMI=()=>{
  const inFlight=React.useRef(false);
  const [tab,setTab]=React.useState('overview'),[data,setData]=React.useState(null),[loading,setLoading]=React.useState(true),[error,setError]=React.useState(''),[installing,setInstalling]=React.useState(false),[clearing,setClearing]=React.useState(false);
  const load=React.useCallback(async(force=false)=>{if(inFlight.current)return;inFlight.current=true;if(force)setLoading(true);setError('');const q=new URLSearchParams();if(tab==='sel')q.set('include','sel');if(force)q.set('refresh','1');try{const r=await fetch('/api/ipmi'+(q.toString()?'?'+q:''),{credentials:'include'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Brak odpowiedzi z kontrolera BMC');setData(d);}catch(e){setError(e.message);}finally{inFlight.current=false;setLoading(false);}},[tab]);
  React.useEffect(()=>{setLoading(!data);load();const id=setInterval(()=>{if(!document.hidden)load();},20000);return()=>clearInterval(id);},[load]);
  const install=async()=>{setInstalling(true);try{const r=await fetch('/api/ipmi/install',{method:'POST',credentials:'include'});if(!r.ok)throw new Error('Instalacja ipmitool nie powiodła się');await load(true);}catch(e){setError(e.message);}finally{setInstalling(false);}};
  const clearSEL=async()=>{if(!window.confirm('Wyczyścić cały dziennik zdarzeń SEL? Tej operacji nie można cofnąć.'))return;setClearing(true);try{const r=await fetch('/api/ipmi/sel/clear',{method:'POST',credentials:'include'});if(!r.ok)throw new Error('Nie udało się wyczyścić SEL');await load(true);}catch(e){setError(e.message);}finally{setClearing(false);}};
  if(loading&&!data)return <div className="ipmi-loading"><div className="ipmi-spinner"/><b>Odczyt kontrolera BMC…</b><span>Pełna lista czujników ma limit 15 sekund</span></div>;
  if(data&&!data.installed)return <IPMIEmpty missing onInstall={install} busy={installing}/>;
  if(!data||!data.bmc_present)return <div className="col" style={{gap:16}}><IPMIEmpty/>{error&&<div className="ipmi-error">{error}</div>}<IPMICoolingDiagnostics/></div>;
  const sensors=data.sensors||[],temps=sensors.filter(s=>s.unit==='°C'&&ipmiHasValue(s)),fans=sensors.filter(ipmiIsFan),alerts=sensors.map(s=>({...s,status:ipmiStatus(s)})).filter(s=>['crit','warn'].includes(s.status)).sort((a,b)=>ipmiRank[a.status]-ipmiRank[b.status]),hottest=temps.length?temps.reduce((a,b)=>Number(a.val)>Number(b.val)?a:b):null,psuOK=[data.power?.psu1?.status,data.power?.psu2?.status].filter(s=>s==='OK').length,g={temps,fans,alerts,hottest,psuOK};
  const tabs=[['overview','Przegląd'],['map','Mapa cieplna'],['sensors','Czujniki'],['fans','Chłodzenie'],['power','Zasilanie'],['sel','Zdarzenia SEL'],['bmc','iLO / BMC']];
  return <div className="col ipmi-page" style={{gap:'var(--gutter)'}}><div className="ipmi-toolbar"><div><div className="row gap-sm"><IPMIStatusBadge status={data.stale||error?'warn':'ok'} text={data.stale||error?'DANE NIEAKTUALNE':'ODCZYT IPMI'}/><span className="mono dim">{data.last_updated?new Date(data.last_updated*1000).toLocaleTimeString('pl'):'—'}</span></div><div className="card-sub">{data.bmc?.model} · {sensors.length} czujników</div></div><button className="btn sm" onClick={()=>load(true)} disabled={loading}><Icon name="refresh" size={12}/>{loading?'Odświeżanie…':'Odśwież teraz'}</button></div>{error&&<div className="ipmi-error"><Icon name="close" size={14}/><span>{error}</span><button className="btn sm" onClick={()=>load(true)}>Ponów</button></div>}{data.stale&&<div className="ipmi-stale"><Icon name="clock" size={14}/><span>iLO nie odpowiedziało — pokazuję ostatni poprawny odczyt i ograniczam kolejne próby, aby nie blokować serwera.</span></div>}<div className="tabs ipmi-tabs">{tabs.map(([id,label])=><div key={id} className={'tab '+(tab===id?'active':'')} onClick={()=>setTab(id)}>{label}{id==='sel'&&data.sel_entries>0&&<span className="badge warn">{data.sel_entries}</span>}{id==='sensors'&&alerts.length>0&&<span className="badge warn">{alerts.length}</span>}</div>)}</div>{tab==='overview'&&<IPMIOverview I={data} g={g} history={data.history||[]} onTab={setTab}/>} {tab==='map'&&<IPMIHeatMap sensors={sensors}/>} {tab==='sensors'&&<IPMISensors sensors={sensors}/>} {tab==='fans'&&<IPMICooling sensors={sensors} stale={data.stale||!!error}/>} {tab==='power'&&<IPMIPower I={data} history={data.history||[]}/>} {tab==='sel'&&<IPMISEL I={data} clearing={clearing} onClear={clearSEL}/>} {tab==='bmc'&&<IPMIBMC I={data} onRefresh={()=>load(true)}/>}</div>;
};

window.IPMI=IPMI;

function IPMICoolingDiagnostics(){
  const [busy,setBusy]=React.useState(false),[report,setReport]=React.useState(null),[error,setError]=React.useState('');
  const run=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/ipmi/cooling-diagnostics',{credentials:'include'});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'Błąd diagnostyki');setReport(d);}catch(e){setError(e.message);}finally{setBusy(false);}};
  const text=report?`${report.vendor} ${report.model}\n${report.collected_at}\n\n${report.results.map(r=>`$ ${r.command}\nCzas: ${r.duration_ms} ms\n${r.output||'(brak wyniku)'}${r.error?'\nBŁĄD: '+r.error:''}`).join('\n\n')}\n\n${report.message}`:'';
  const download=()=>{const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nimbus-chlodzenie-ipmi.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <div className="card"><div className="card-head"><div><div className="card-title">Diagnostyka iLO i chłodzenia</div><div className="card-sub">Model, firmware, wentylatory, temperatury i ostatnie zdarzenia sprzętowe</div></div></div><div className="card-body col" style={{gap:14}}><p>Raport pomoże ustalić, co udostępnia Twój kontroler i gdzie zanika odczyt. Diagnostyka zatrzymuje się po przekroczeniu czasu odpowiedzi BMC.</p><div className="row gap-sm"><button className="btn primary" disabled={busy} onClick={run}>{busy?'Odczytywanie iLO…':'Uruchom diagnostykę'}</button>{report&&<button className="btn" onClick={download}>Pobierz raport</button>}</div>{error&&<div className="ipmi-error" role="alert">{error}</div>}{report&&<pre className="ipmi-diagnostics-output">{text}</pre>}</div></div>;
}
function IPMICooling({sensors,stale}){
  const fans=sensors.filter(ipmiIsFan),missing=sensors.filter(s=>s.unit==='°C'&&!ipmiHasValue(s));
  return <div className="col" style={{gap:16}}><div className="card"><div className="card-head"><div><div className="card-title">Wentylatory serwera</div><div className="card-sub">RPM, procenty i stany udostępniane przez BMC — bez przeliczania procentów na obroty</div></div><IPMIStatusBadge status="unknown" text="STEROWANIE NIEPOTWIERDZONE"/></div><div className="card-body col" style={{gap:15}}>{(stale||missing.length>0)&&<div className="ipmi-stale">{stale?'Dane są nieaktualne. ':''}{missing.length>0?`${missing.length} czujników temperatury nie zwraca wartości (także możliwe nieobsadzone gniazda). `:''}Brak temperatur może towarzyszyć awaryjnemu zwiększeniu obrotów; sam ten odczyt nie rozstrzyga przyczyny.</div>}<div className="ipmi-fan-grid">{fans.map((f,i)=><div className="ipmi-fan-card" key={i}><Icon name="fan" size={26}/><b>{f.name}</b><strong>{ipmiValue(f)}</strong><IPMIStatusBadge status={stale?'unknown':ipmiStatus(f)}/><small className="dim">Stan BMC: {f.raw_status||'nieudostępniony'}</small></div>)}</div>{!fans.length&&<p>Lista IPMI nie zawiera rozpoznanych wentylatorów. Uruchom diagnostykę poniżej, aby sprawdzić osobny odczyt SDR.</p>}<p>Ręczne sterowanie wymaga interfejsu obsługiwanego przez konkretny model i firmware iLO. Nimbus nie ma jeszcze potwierdzonej metody dla tego kontrolera. Przy utracie temperatur nie należy wymuszać niższych obrotów.</p></div></div><IPMICoolingDiagnostics/></div>;
}
