const kvmRequest=async(path,body,method)=>{
  const response=await fetch('/api/kvm/'+path,{credentials:'include',method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
  let data;try{data=await response.json();}catch{throw new Error(`Nieprawidłowa odpowiedź serwera (HTTP ${response.status}).`);}
  if(!response.ok||data?.error)throw new Error(data?.error||`Błąd serwera (HTTP ${response.status}).`);
  return data;
};
const kvmStates={running:['Uruchomiona','ok'],stopped:['Wyłączona','muted'],paused:['Wstrzymana','warn'],shutting_down:['Zamykanie','warn']};
const kvmState=state=>kvmStates[state]||['Stan nieznany','warn'];
const kvmMemory=value=>Number.isFinite(value)?`${(value/1024).toLocaleString('pl-PL',{maximumFractionDigits:1})} GiB`:'—';
const kvmFilter=(vms,query,state)=>vms.filter(v=>(state==='all'||v.state===state)&&[v.name,v.os,v.ip,v.network,v.mac,...(v.ips||[])].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
const kvmActions=state=>state==='running'?[['stop','Wyłącz','stop'],['pause','Wstrzymaj','pause'],['restart','Restart','refresh']]:state==='paused'?[['resume','Wznów','play']]:state==='stopped'?[['start','Uruchom','play']]:[];
const KVMState=({state,busy})=><span className={'kv-state '+(busy?'warn':kvmState(state)[1])}><i/>{busy?'Wykonywanie…':kvmState(state)[0]}</span>;
const KVMFacts=({vm})=><dl className="kv-facts">{[['Procesory',`${vm.cpu??'—'} vCPU`],['Przydzielony RAM',kvmMemory(vm.ram)],['Dysk wirtualny',vm.disk||'—'],['Sieć',vm.network||'—'],['Adresy IP',(vm.ips?.length?vm.ips.join(', '):vm.ip)||'—'],['MAC',vm.mac||'—'],['VLAN',vm.vlan||'—'],['Czas pracy',vm.uptime||'—']].map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v}</dd></React.Fragment>)}</dl>;
function KVMSnapshots({vm,onChange}){
  const [snaps,setSnaps]=React.useState(null),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[name,setName]=React.useState(''),[remove,setRemove]=React.useState(null);
  const base='snapshots?vm='+encodeURIComponent(vm.id);
  const load=React.useCallback(async()=>{try{const d=await kvmRequest(base);if(!Array.isArray(d.snapshots))throw new Error('Brak listy snapshotów w odpowiedzi.');setSnaps(d.snapshots);setError('');}catch(e){setError(e.message);}},[base]);
  React.useEffect(()=>{load();},[load]);
  const mutate=async deleting=>{if(busy)return;setBusy(true);setError('');try{await kvmRequest(base+(deleting?'&snap='+encodeURIComponent(remove):''),deleting?null:{name:name.trim()||'snap-'+Date.now(),desc:'Utworzono w Nimbus'},deleting?'DELETE':'POST');setName('');setRemove(null);await load();onChange();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <section className="kv-panel"><div className="kv-section-head"><div><h3>Snapshoty</h3><p>Zapisany stan maszyny w libvirt</p></div><button className="btn sm" onClick={load} disabled={busy}>Odśwież</button></div>{error&&<div className="kv-alert" role="alert">{error}</div>}<form className="kv-toolbar" onSubmit={e=>{e.preventDefault();return mutate(false);}}><input aria-label="Nazwa snapshota" placeholder="Nazwa snapshota (opcjonalna)" value={name} onChange={e=>setName(e.target.value)} disabled={busy}/><button className="btn primary" disabled={busy}>{busy?'Wykonywanie…':'Utwórz snapshot'}</button></form>{snaps===null?<div className="kv-empty">{error?'Nie udało się pobrać snapshotów.':'Pobieranie snapshotów…'}</div>:snaps.length===0?<div className="kv-empty">Ta maszyna nie ma jeszcze snapshotów.</div>:<div className="kv-table-wrap"><table className="table"><thead><tr><th>Nazwa</th><th>Utworzono</th><th>Akcja</th></tr></thead><tbody>{snaps.map(s=><tr key={s.name}><td className="mono">{s.name}</td><td>{Number(s.date)>0?new Date(Number(s.date)*1000).toLocaleString('pl-PL'):s.date||'—'}</td><td><button className="btn sm" disabled={busy} onClick={()=>setRemove(s.name)}>Usuń snapshot</button></td></tr>)}</tbody></table></div>}{remove&&<div className="kv-confirm"><p>Usunąć snapshot <strong>{remove}</strong>?</p><button className="btn" disabled={busy} onClick={()=>setRemove(null)}>Anuluj</button><button className="btn danger" disabled={busy} onClick={()=>mutate(true)}>Usuń snapshot</button></div>}</section>;
}
function KVMWorkspace(){
  const panels=window.KVMPanels;
  const [vms,setVms]=React.useState([]),[status,setStatus]=React.useState(null),[loading,setLoading]=React.useState(true),[fetchError,setFetchError]=React.useState(''),[actionError,setActionError]=React.useState(''),[notice,setNotice]=React.useState(''),[updated,setUpdated]=React.useState(null);
  const [tab,setTab]=React.useState(()=>{const tab=window.__nimbusKVMTab;delete window.__nimbusKVMTab;return tab==='templates'?'templates':'vms'}),[query,setQuery]=React.useState(''),[filter,setFilter]=React.useState('all'),[view,setView]=React.useState('grid'),[selected,setSelected]=React.useState(null),[detailTab,setDetailTab]=React.useState('overview'),[dialog,setDialog]=React.useState(null),[pending,setPending]=React.useState({}),[confirm,setConfirm]=React.useState(null),[installing,setInstalling]=React.useState(false);
  const inflight=React.useRef(null),alive=React.useRef(false),locks=React.useRef(new Set());
  const load=React.useCallback(()=>{
    if(inflight.current)return inflight.current;
    inflight.current=(async()=>{try{const [list,health]=await Promise.all([kvmRequest('vms'),kvmRequest('status')]);if(!Array.isArray(list.vms)||typeof health.installed!=='boolean')throw new Error('Niepełna odpowiedź KVM.');if(alive.current){setVms(list.vms);setStatus(health);setUpdated(new Date());setFetchError('');}}catch(e){if(alive.current)setFetchError(e.message);}finally{if(alive.current)setLoading(false);inflight.current=null;}})();
    return inflight.current;
  },[]);
  React.useEffect(()=>{alive.current=true;let timer;const poll=async()=>{await load();if(alive.current)timer=setTimeout(poll,10000);};poll();return()=>{alive.current=false;clearTimeout(timer);};},[load]);
  const action=async(vm,act)=>{
    if(locks.current.has(vm.id))return;
    locks.current.add(vm.id);setPending(p=>({...p,[vm.id]:act}));setActionError('');setNotice('');
    try{await kvmRequest('action',{vm:vm.id,action:act});setNotice(`Przyjęto polecenie dla ${vm.name}. Stan zostanie odczytany z libvirt.`);if(inflight.current)await inflight.current;await load();setConfirm(null);}catch(e){setActionError(`${vm.name}: ${e.message}`);}finally{locks.current.delete(vm.id);if(alive.current)setPending(p=>{const next={...p};delete next[vm.id];return next;});}
  };
  const install=async()=>{setInstalling(true);setActionError('');try{await kvmRequest('install',{});await load();setNotice('Zakończono instalację pakietów KVM.');}catch(e){setActionError(e.message);}finally{setInstalling(false);}};
  const select=vm=>{setSelected(vm.id);setDetailTab('overview');};
  const show=(kind,vm)=>setDialog({kind,vm});
  const vm=vms.find(v=>v.id===selected),visible=kvmFilter(vms,query,filter),running=vms.filter(v=>v.state==='running').length;
  const buttons=v=><div className="kv-actions">{kvmActions(v.state).map(([act,label,icon])=><button key={act} className={'btn sm '+(act==='start'||act==='resume'?'primary':'')} disabled={!!pending[v.id]} onClick={()=>act==='restart'?setConfirm({vm:v,act,label:'Uruchomić ponownie'}):action(v,act)}><window.Icon name={icon} size={12}/>{label}</button>)}<button className="btn sm" disabled={v.state!=='running'||!!pending[v.id]} onClick={()=>show('vnc',v)}><window.Icon name="terminal" size={12}/>Konsola</button></div>;
  const tabs=[['vms','Maszyny'],['templates','Gotowe systemy'],['iso','Biblioteka ISO'],['config','Ustawienia hosta']];
  return <div className="kv-workspace">
    <header className="kv-header"><div><div className="kv-eyebrow">NIMBUS / WIRTUALIZACJA</div><h2>Maszyny wirtualne<span>KVM</span></h2><p>Systemy, zasoby i konsole w jednym miejscu.</p></div><div className="kv-header-actions"><button className="btn" onClick={load} disabled={loading}><window.Icon name="refresh" size={14}/>Odśwież</button><button className="btn primary" onClick={()=>show('new')} disabled={!status?.installed}><window.Icon name="plus" size={14}/>Nowa maszyna</button></div></header>
    <div className="kv-host"><span className={'kv-state '+(status?.running?'ok':'warn')}><i/>{!status?'Odczytywanie hosta':status.running?'Usługa libvirt aktywna':'Usługa libvirt nieaktywna'}</span><span>{status?.cpu_virt?.supported?status.cpu_virt.type:'Wirtualizacja CPU: '+(status?'niedostępna':'—')}</span><span className="kv-updated">{updated?'Odczyt: '+updated.toLocaleTimeString('pl-PL'):'Oczekiwanie na dane'}{fetchError?' · dane nieaktualne':''}</span></div>
    {fetchError&&<div className="kv-alert" role="alert">Nie udało się odświeżyć KVM: {fetchError} <button className="btn sm" onClick={load}>Ponów</button></div>}{actionError&&<div className="kv-alert" role="alert">{actionError}</div>}{notice&&<div className="kv-notice" role="status">{notice}</div>}
    <div className="kv-stats">{[['Maszyny',updated?vms.length:'—',`${running} uruchomionych`,'cpu'],['Przydzielone vCPU',updated?vms.reduce((s,v)=>s+(v.cpu||0),0):'—','Wszystkie maszyny','cpu'],['Przydzielony RAM',updated?kvmMemory(vms.reduce((s,v)=>s+(v.ram||0),0)):'—','Konfiguracja maszyn','ram'],['Snapshoty',updated?vms.reduce((s,v)=>s+(v.snapshot||0),0):'—','Zapisane w libvirt','disk']].map(([label,value,sub,icon])=><div className="kv-stat" key={label}><span>{label}<window.Icon name={icon} size={16}/></span><strong>{value}</strong><small>{sub}</small></div>)}</div>
    <nav className="kv-tabs" aria-label="Wirtualizacja">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}{id==='vms'&&<span>{vms.length}</span>}</button>)}</nav>
    {status?.installed===false?<section className="kv-panel kv-empty"><window.Icon name="cpu" size={32}/><h3>Przygotuj host do wirtualizacji</h3><p>Zainstaluj KVM i libvirt, aby tworzyć i uruchamiać maszyny.</p><button className="btn primary" disabled={installing} onClick={install}>{installing?'Instalowanie…':'Zainstaluj KVM + libvirt'}</button></section>:loading&&!updated?<div className="kv-empty">Pobieranie maszyn i stanu hosta…</div>:<>
    {tab==='vms'&&(selected?<><button className="kv-back" onClick={()=>setSelected(null)}>← Wszystkie maszyny</button>{!vm?<div className="kv-panel kv-empty">Maszyna nie jest już dostępna na liście hosta.</div>:<><section className="kv-panel"><div className="kv-section-head"><div className="kv-identity"><div className="kv-machine-icon"><window.Icon name="cpu" size={24}/></div><div><h3>{vm.name}</h3><p>{vm.os||'System nieznany'} · {vm.id}</p></div></div><KVMState state={vm.state} busy={pending[vm.id]}/></div><div className="kv-detail-actions">{buttons(vm)}<button className="btn sm" onClick={()=>show('remote',vm)}>Dostęp VNC</button></div><div className="kv-tabs kv-inner-tabs">{[['overview','Zasoby i sieć'],['snapshots','Snapshoty']].map(([id,label])=><button key={id} className={detailTab===id?'active':''} onClick={()=>setDetailTab(id)}>{label}</button>)}</div>{detailTab==='overview'&&<KVMFacts vm={vm}/>}</section>{detailTab==='snapshots'&&<KVMSnapshots key={vm.id} vm={vm} onChange={load}/>}<section className="kv-panel kv-danger"><div><h3>Zasilanie i usuwanie</h3><p>Wymuszone wyłączenie przerywa pracę systemu gościa.</p></div><div className="kv-actions"><button className="btn sm" disabled={!['running','paused','shutting_down'].includes(vm.state)||!!pending[vm.id]} onClick={()=>setConfirm({vm,act:'force-stop',label:'Wymusić wyłączenie'})}>Wymuś wyłączenie</button><button className="btn sm danger" disabled={!!pending[vm.id]} onClick={()=>show('delete',vm)}>Usuń maszynę</button></div></section></>}</>:<>
    <div className="kv-toolbar"><label className="kv-search"><window.Icon name="search" size={16}/><input aria-label="Szukaj maszyn" placeholder="Szukaj po nazwie, IP lub sieci…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filtr stanu" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Wszystkie stany</option>{Object.entries(kvmStates).map(([id,[label]])=><option key={id} value={id}>{label}</option>)}</select><div className="kv-switch">{[['grid','Kafelki'],['list','Lista']].map(([id,label])=><button key={id} aria-pressed={view===id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</div></div>
    {!visible.length?<section className="kv-panel kv-empty"><window.Icon name="cpu" size={32}/><h3>{vms.length?'Brak pasujących maszyn':fetchError?'Lista maszyn niedostępna':'Miejsce na Twój kolejny system'}</h3><p>{vms.length?'Zmień wyszukiwanie lub filtr.':fetchError?'Ponów odczyt hosta.':'Utwórz maszynę z ISO lub wybierz gotowy system.'}</p>{!vms.length&&!fetchError&&<button className="btn primary" onClick={()=>setTab('templates')}>Przeglądaj gotowe systemy</button>}</section>:view==='grid'?<div className="kv-grid">{visible.map(v=><article className="kv-vm" key={v.id}><div className="kv-vm-top"><div className="kv-machine-icon"><window.Icon name="cpu" size={22}/></div><KVMState state={v.state} busy={pending[v.id]}/></div><button className="kv-vm-name" onClick={()=>select(v)}>{v.name}</button><p className="kv-vm-os">{v.os||'System nieznany'} · {v.network||'Brak danych sieci'}</p><div className="kv-vm-resources"><div><strong>{v.cpu??'—'}</strong><small>vCPU</small></div><div><strong>{kvmMemory(v.ram)}</strong><small>RAM</small></div><div><strong>{v.disk||'—'}</strong><small>Dysk</small></div></div><div className="kv-vm-ip"><window.Icon name="network" size={13}/><span>{v.ip||'Brak adresu IP'}</span><button onClick={()=>select(v)}>Szczegóły →</button></div><footer>{buttons(v)}</footer></article>)}</div>:<section className="kv-panel kv-table-wrap"><table className="table"><thead><tr><th>Maszyna</th><th>Stan</th><th>vCPU / RAM</th><th>Adres IP / sieć</th><th>Akcje</th></tr></thead><tbody>{visible.map(v=><tr key={v.id}><td><button className="kv-vm-name" onClick={()=>select(v)}>{v.name}</button><small className="kv-table-sub">{v.os}</small></td><td><KVMState state={v.state} busy={pending[v.id]}/></td><td>{v.cpu} / {kvmMemory(v.ram)}</td><td className="mono">{v.ip||'—'}<small className="kv-table-sub">{v.network||'—'}</small></td><td>{buttons(v)}</td></tr>)}</tbody></table></section>}<div className="kv-list-foot">{visible.length} z {vms.length} maszyn · automatyczne odświeżanie</div>
    </>)}
    {tab==='templates'&&<panels.KVMTemplatesPanel onReady={load}/>} {tab==='iso'&&<panels.KVMISOPanel kvmStatus={status}/>} {tab==='config'&&<panels.KVMConfigPanel kvmStatus={status} setKvmStatus={setStatus}/>}
    </>}
    {dialog?.kind==='new'&&<panels.NewVmDialog kvmStatus={status} onClose={()=>setDialog(null)} onAdd={load}/>}{dialog?.kind==='vnc'&&<panels.VncConsole vm={dialog.vm} onClose={()=>setDialog(null)}/>}{dialog?.kind==='remote'&&<panels.VncRemoteDialog vm={dialog.vm} onClose={()=>setDialog(null)}/>}{dialog?.kind==='delete'&&<panels.DeleteVmDialog vm={dialog.vm} onClose={()=>setDialog(null)} onDeleted={()=>{setDialog(null);setSelected(null);load();}}/>}
    {confirm&&<window.Modal title={`${confirm.label} ${confirm.vm.name}?`} onClose={()=>{if(!pending[confirm.vm.id])setConfirm(null);}} footer={<><button className="btn" disabled={!!pending[confirm.vm.id]} onClick={()=>setConfirm(null)}>Anuluj</button><button className="btn danger" disabled={!!pending[confirm.vm.id]} onClick={()=>action(confirm.vm,confirm.act)}>{pending[confirm.vm.id]?'Wykonywanie…':confirm.label}</button></>}><p>{confirm.act==='force-stop'?'Niezapisane dane w maszynie mogą zostać utracone.':'System gościa otrzyma polecenie ponownego uruchomienia.'}</p>{actionError&&<div className="kv-alert" role="alert">{actionError}</div>}</window.Modal>}
  </div>;
}
window.KvmVirtualization=KVMWorkspace;window.KVMScreen=KVMWorkspace;
