// Docker workspace: server-confirmed state, bounded polling and persistent detail views.
const {useState,useEffect,useRef,useCallback,useMemo}=React;
const DI=window.Icon;
const dockerAPI=async(path,options={})=>{
  const r=await fetch(path,{credentials:'include',...options,headers:{'Content-Type':'application/json',...options.headers}});
  const d=await r.json().catch(()=>({error:`Nieprawidłowa odpowiedź serwera (HTTP ${r.status})`}));
  if(!r.ok||d.error){const error=new Error(d.error||`HTTP ${r.status}`);error.data=d;throw error;}
  return d;
};
function useDockerPoll(path,ms=8000){
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[updated,setUpdated]=useState(null);
  const controller=useRef(),alive=useRef(true);
  const refresh=useCallback(async()=>{
    if(!path)return;
    controller.current?.abort();const c=new AbortController();controller.current=c;setLoading(true);
    try{const d=await dockerAPI(path,{signal:c.signal});if(alive.current&&!c.signal.aborted){setData(d);setError('');setUpdated(new Date());}}
    catch(e){if(alive.current&&e.name!=='AbortError')setError(e.message);}
    finally{if(alive.current&&!c.signal.aborted)setLoading(false);}
  },[path]);
  useEffect(()=>{alive.current=true;setData(null);setError('');refresh();return()=>{alive.current=false;controller.current?.abort();};},[refresh]);
  useEffect(()=>{if(!ms)return;const timer=setInterval(()=>{if(!document.hidden)refresh();},ms);return()=>clearInterval(timer);},[refresh,ms]);
  return {data,error,loading,updated,refresh};
}
const stateNames={running:'Działa',exited:'Zatrzymany',stopped:'Zatrzymany',created:'Utworzony',paused:'Wstrzymany',restarting:'Restartuje',removing:'Usuwany',dead:'Awaria',unknown:'Nieznany',partial:'Częściowo działa',problem:'Wymaga uwagi'};
const problem=c=>c.health==='unhealthy'||['restarting','dead','problem'].includes(c.state||c.status);
const statusTone=c=>problem(c)?'bad':c.health==='starting'||['paused','partial'].includes(c.state||c.status)?'warn':(c.state||c.status)==='running'?'good':'neutral';
const DCStatus=({c})=><span className={`dc-status ${statusTone(c)}`}><i/>{c.health==='unhealthy'?'Błąd healthchecka':c.health==='starting'?'Rozruch':stateNames[c.state||c.status]||c.state||c.status||'Nieznany'}</span>;
const DCError=({children})=>children?<div className="dc-alert" role="alert"><DI name="shield" size={17}/><span>{children}</span></div>:null;
const DCEmpty=({title,children})=><div className="dc-empty"><DI name="docker" size={34}/><h3>{title}</h3><p>{children}</p></div>;
const memText=n=>n>=1024?`${(n/1024).toFixed(1)} GiB`:`${Math.round(n)} MiB`;
const dateText=d=>d&&!d.startsWith('0001')?new Date(d).toLocaleString('pl-PL'):'—';
const category=c=>/jellyfin|plex|emby|sonarr|radarr|lidarr|transmission|qbittorrent/i.test(c.image)?'Media':/traefik|nginx|caddy|pihole|adguard|wireguard/i.test(c.image)?'Sieć':/grafana|prometheus|uptime|netdata|glances/i.test(c.image)?'Monitoring':'Pozostałe';
function DCLogo({c}){const colors=['#4f8cff','#ad86ff','#42bfa5','#e5a253'];const hash=Array.from(c.name||'?').reduce((a,v)=>a+v.charCodeAt(0),0);return <span className="dc-logo" style={{'--app-color':colors[hash%colors.length]}}>{(c.name||'?').replace(/[^a-z0-9]/ig,'').slice(0,2).toUpperCase()}</span>;}
function DCButton({icon,children,...props}){return <button className="btn" {...props}>{icon&&<DI name={icon} size={15}/>}<span>{children}</span></button>;}
function DCActions({c,busy,onAction}){return <div className="dc-actions">{c.state==='paused'?<DCButton disabled={busy} icon="play" onClick={()=>onAction(c,'unpause')}>Wznów</DCButton>:['running','restarting'].includes(c.state)?<><DCButton disabled={busy} icon="restart" onClick={()=>onAction(c,'restart')}>Restart</DCButton><DCButton disabled={busy} icon="stop" onClick={()=>onAction(c,'stop')}>Stop</DCButton></>:<DCButton disabled={busy||c.state==='removing'} icon="play" onClick={()=>onAction(c,'start')}>Uruchom</DCButton>}</div>;}
function DCKPI({label,value,sub,icon,tone}){return <div className={`dc-kpi ${tone||''}`}><span className="dc-kpi-label"><DI name={icon} size={16}/>{label}</span><strong>{value}</strong><small>{sub}</small></div>;}
function DockerWorkspace(){
  const poll=useDockerPoll('/services/docker/containers');
  const containers=Array.isArray(poll.data?.containers)?poll.data.containers:[];
  const [tab,setTab]=useState('containers'),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[group,setGroup]=useState('project'),[view,setView]=useState('list');
  const [busy,setBusy]=useState({}),[actionError,setActionError]=useState(''),[notice,setNotice]=useState(''),[newContainer,setNewContainer]=useState(false),[confirm,setConfirm]=useState(null);
  const busyRef=useRef(new Set());
  const [history,setHistory]=useState({});
  useEffect(()=>{if(!poll.data)return;setHistory(old=>{const next={};for(const c of containers){const points=old[c.id]||[];next[c.id]=c.stats_available?[...points,{time:Date.now(),cpu:c.cpu,mem:c.mem}].slice(-40):points;}return next;});},[poll.data]);
  const act=async(c,action)=>{
    if(busyRef.current.has(c.id))return;busyRef.current.add(c.id);setBusy(b=>({...b,[c.id]:action}));setActionError('');setNotice('');
    try{await dockerAPI(`/services/docker/container/${encodeURIComponent(c.id)}${action==='remove'?'':`/${action}`}`,{method:action==='remove'?'DELETE':'POST'});setNotice(`${c.name}: ${action==='remove'?'kontener usunięty':'polecenie wykonane'}.`);if(action==='remove')setSelected(null);await poll.refresh();}
    catch(e){setActionError(`${c.name}: ${e.message}`);await poll.refresh();}
    finally{busyRef.current.delete(c.id);setBusy(b=>({...b,[c.id]:null}));setConfirm(null);}
  };
  const current=containers.find(c=>c.id===selected);
  const running=containers.filter(c=>c.state==='running');const measured=running.filter(c=>c.stats_available);const issues=containers.filter(problem);
  const filtered=containers.filter(c=>`${c.name} ${c.image} ${c.project||''}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='problem'&&problem(c)||filter==='running'&&c.state==='running'||filter==='stopped'&&!['running','restarting','paused'].includes(c.state)));
  const groups=useMemo(()=>{const result={};for(const c of filtered){const key=group==='project'?(c.project||'Samodzielne kontenery'):group==='category'?category(c):'Wszystkie aplikacje';(result[key]??=[]).push(c);}return Object.entries(result).sort(([a,ac],[b,bc])=>Number(bc.some(problem))-Number(ac.some(problem))||a.localeCompare(b)).map(([name,items])=>[name,items.sort((a,b)=>Number(problem(b))-Number(problem(a))||a.name.localeCompare(b.name))]);},[poll.data,query,filter,group]);
  const changeTab=t=>{setTab(t);setSelected(null);setActionError('');};
  const tabs=[['containers','Aplikacje'],['compose','Projekty Compose'],['images','Obrazy'],['volumes','Wolumeny'],['networks','Sieci'],['templates','Szablony'],['topology','Topologia']];
  const Legacy=window.DockerLegacyTabs?.[tab];
  return <div className="dc-workspace">
    <header className="dc-heading"><div><div className="dc-eyebrow"><DI name="docker" size={17}/> DOCKER WORKSPACE</div><h1>{selected?'Szczegóły aplikacji':'Twoje aplikacje'}</h1><p>Kontenery, projekty i ich dane — w jednym miejscu.</p></div><div className="dc-actions"><DCButton icon="refresh" disabled={poll.loading} onClick={poll.refresh}>Odśwież</DCButton><button className="btn primary" onClick={()=>setNewContainer(true)}><DI name="plus" size={16}/> Dodaj kontener</button></div></header>
    <nav className="dc-tabs" aria-label="Docker">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>changeTab(id)}>{label}{id==='containers'&&poll.data&&<span>{containers.length}</span>}</button>)}</nav>
    <DCError>{poll.error?`Nie udało się odczytać Dockera. ${poll.error}${poll.data?' Wyświetlane są ostatnie odczytane dane.':''}`:actionError}</DCError>
    {notice&&<div className="dc-notice" role="status">{notice}<button aria-label="Zamknij komunikat" onClick={()=>setNotice('')}>×</button></div>}
    {newContainer&&React.createElement(window.DockerNewContainer,{onClose:()=>setNewContainer(false),onAdd:()=>{changeTab('containers');poll.refresh();}})}
    {confirm&&<window.Modal title="Usunąć kontener?" onClose={()=>!busy[confirm.id]&&setConfirm(null)} footer={<><DCButton disabled={!!busy[confirm.id]} onClick={()=>setConfirm(null)}>Anuluj</DCButton><button className="btn danger" disabled={!!busy[confirm.id]} onClick={()=>act(confirm,'remove')}>{busy[confirm.id]?'Usuwanie…':'Usuń kontener'}</button></>}><p>Usuniesz <strong>{confirm.name}</strong> wraz z jego zapisywalną warstwą. Wolumeny i katalogi hosta zostaną zachowane.</p>{confirm.project&&<p>Kontener należy do projektu <strong>{confirm.project}</strong>. Kolejne wdrożenie Compose może utworzyć go ponownie.</p>}<DCError>{actionError}</DCError></window.Modal>}
    {tab==='containers'&&(selected?current?<DockerDetail key={selected} c={current} history={history[selected]||[]} busy={!!busy[selected]} onBack={()=>setSelected(null)} onAction={act} onRemove={()=>setConfirm(current)} onCompose={()=>changeTab('compose')} onRefresh={poll.refresh}/>:<DCEmpty title={poll.loading?'Odczytywanie kontenera…':'Kontenera nie ma na liście'}><DCButton onClick={()=>setSelected(null)}>Wróć do aplikacji</DCButton></DCEmpty>:<>
      <section className="dc-kpis"><DCKPI icon="docker" label="Uruchomione" value={poll.data?`${running.length} / ${containers.length}`:'—'} sub="kontenerów"/><DCKPI icon="shield" label="Wymagają uwagi" value={poll.data?issues.length:'—'} tone={issues.length?'bad':''} sub="awarie, restarty, healthcheck"/><DCKPI icon="cpu" label="CPU aplikacji" value={measured.length?`${measured.reduce((n,c)=>n+c.cpu,0).toFixed(1)}%`:'—'} sub={measured.length<running.length?`Pomiar ${measured.length} z ${running.length} aplikacji`:'100% odpowiada jednemu rdzeniowi'}/><DCKPI icon="ram" label="Pamięć aplikacji" value={measured.length?memText(measured.reduce((n,c)=>n+c.mem,0)):'—'} sub="bieżące użycie RAM"/></section>
      <div className="dc-toolbar"><label className="dc-search"><DI name="search" size={17}/><input aria-label="Szukaj aplikacji" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Szukaj aplikacji, obrazu lub projektu…"/></label><select aria-label="Grupowanie" value={group} onChange={e=>setGroup(e.target.value)}><option value="project">Według projektu</option><option value="category">Według kategorii</option><option value="none">Bez grupowania</option></select><div className="dc-view"><button aria-label="Widok listy" aria-pressed={view==='list'} className={view==='list'?'active':''} onClick={()=>setView('list')}><DI name="log" size={17}/></button><button aria-label="Widok kafelków" aria-pressed={view==='grid'} className={view==='grid'?'active':''} onClick={()=>setView('grid')}><DI name="grid" size={17}/></button></div></div>
      <div className="dc-filterbar"><div className="dc-filters">{[['all','Wszystkie'],['running','Działające'],['problem','Wymagają uwagi'],['stopped','Zatrzymane']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}{id==='problem'&&issues.length>0&&<span>{issues.length}</span>}</button>)}</div><small>{poll.loading?'Odświeżanie…':poll.updated?`Odczyt ${poll.updated.toLocaleTimeString('pl-PL')}`:'Brak odczytu'}</small></div>
      {!poll.data&&poll.loading?<DCEmpty title="Odczytywanie aplikacji…">Pobieram stan z silnika Docker.</DCEmpty>:!filtered.length?<DCEmpty title={containers.length?'Brak pasujących aplikacji':poll.error?'Docker jest niedostępny':'Tutaj pojawią się Twoje aplikacje'}>{containers.length?'Zmień wyszukiwanie lub filtr.':poll.error?'Sprawdź usługę Docker i ponów odczyt.':'Dodaj kontener albo utwórz projekt Compose.'}</DCEmpty>:groups.map(([name,items])=><section className="dc-group" key={name}><div className="dc-group-heading"><h2><DI name={group==='project'&&name!=='Samodzielne kontenery'?'folder':'docker'} size={16}/>{name}<span>{items.length}</span></h2><small>{items.filter(c=>c.state==='running').length} działa</small></div><div className={`dc-containers ${view}`}>{view==='list'&&<div className="dc-list-head"><span>Aplikacja / obraz</span><span>Stan</span><span>CPU / RAM</span><span>Porty hosta</span><span>Akcje</span></div>}{items.map(c=><article key={c.id} className={`dc-container ${problem(c)?'has-problem':''}`}><button className="dc-app" onClick={()=>setSelected(c.id)}><DCLogo c={c}/><span><strong>{c.name}</strong><small title={c.image}>{c.image}</small></span></button><div><DCStatus c={c}/><small className="dc-uptime">{busy[c.id]?'Trwa operacja…':c.uptime}</small></div><div className="dc-resource"><strong>{c.stats_available?`${c.cpu.toFixed(1)}%`:'—'}</strong><small>{c.stats_available?memText(c.mem):c.state==='running'?'Oczekiwanie na pomiar':'Brak pomiaru'}</small></div><div className="dc-ports" title={c.ports}>{c.ports||'Brak publikowanych portów'}<DockerAppLink c={c}/></div><DCActions c={c} busy={!!busy[c.id]} onAction={act}/></article>)}</div></section>)}
    </>)}
    {tab==='compose'&&<DockerProjects onChanged={poll.refresh}/>}
    {Legacy&&<Legacy onInstalled={()=>changeTab('compose')}/>}
    {tab==='topology'&&window.DockerTopology&&<window.DockerTopology/>}
  </div>;
}
function DockerDetail({c,history,busy,onBack,onAction,onRemove,onCompose,onRefresh}){
  const [tab,setTab]=useState('overview');const poll=useDockerPoll(`/api/docker/inspect/${encodeURIComponent(c.id)}`);const raw=poll.data?.raw;const state=raw?.State||{};
  const [reveal,setReveal]=useState(false);
  return <div className="dc-detail"><button className="dc-back" onClick={onBack}>← Wszystkie aplikacje</button><div className="dc-detail-heading"><div className="dc-app"><DCLogo c={c}/><div><h2>{c.name}</h2><p>{c.image}</p></div><DCStatus c={c}/></div><DCActions c={c} busy={busy} onAction={onAction}/></div><div className="dc-subnav">{[['overview','Przegląd'],['logs','Logi'],['terminal','Terminal'],['config','Konfiguracja'],['data','Dane i montowania'],['network','Sieć']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><DCError>{poll.error}</DCError>
    {tab==='logs'?<DockerLogs id={c.id}/>:tab==='terminal'?c.state==='running'?<DockerTerminal id={c.id}/>:<DCEmpty title="Terminal wymaga działającego kontenera">Uruchom lub wznów aplikację.</DCEmpty>:!raw?<DCEmpty title={poll.error?'Szczegóły niedostępne':'Pobieranie szczegółów…'}/>:<>
      {tab==='overview'&&<><div className="dc-kpis"><DCKPI icon="cpu" label="CPU" value={c.stats_available?`${c.cpu.toFixed(1)}%`:'—'} sub="bieżące obciążenie"/><DCKPI icon="ram" label="Pamięć" value={c.stats_available?memText(c.mem):'—'} sub={raw.HostConfig?.Memory?`Limit ${memText(raw.HostConfig.Memory/1048576)}`:'Bez limitu RAM'}/><DCKPI icon="restart" label="Restarty" value={raw.RestartCount??'—'} sub="licznik Dockera"/><DCKPI icon="shield" label="Healthcheck" value={state.Health?.Status==='healthy'?'OK':state.Health?.Status==='unhealthy'?'Błąd':state.Health?.Status==='starting'?'Rozruch':'Brak'} sub={state.Health?'wynik ostatniego sprawdzenia':'Nie skonfigurowano sprawdzania'}/></div>
      {(state.Error||state.OOMKilled||state.ExitCode!==0&&state.Status==='exited')&&<DCError>{state.OOMKilled?'Kontener został zakończony z powodu braku pamięci. ':''}{state.Error||`Kod wyjścia: ${state.ExitCode}`}</DCError>}
      <div className="dc-two"><section className="dc-panel"><h3>Obciążenie CPU <small>historia od otwarcia widoku</small></h3>{history.length>1?<div className="dc-chart"><window.LineChart series={[history.map(p=>p.cpu)]} colors={['var(--accent)']} height={140}/><div><span>{new Date(history[0].time).toLocaleTimeString('pl-PL')}</span><span>{new Date(history.at(-1).time).toLocaleTimeString('pl-PL')}</span></div></div>:<p className="dc-muted">Wykres pojawi się po dwóch pomiarach.</p>}</section><section className="dc-panel"><h3>Informacje o kontenerze</h3><dl className="dc-facts"><dt>ID</dt><dd>{c.id}</dd><dt>Utworzony</dt><dd>{dateText(raw.Created)}</dd><dt>Uruchomiony</dt><dd>{dateText(state.StartedAt)}</dd><dt>Projekt Compose</dt><dd>{c.project?<button className="dc-link" onClick={onCompose}>{c.project} →</button>:'Samodzielny kontener'}</dd><dt>Restart</dt><dd>{raw.HostConfig?.RestartPolicy?.Name||'no'}</dd></dl></section></div>
      {state.Health?.Log?.length>0&&<section className="dc-panel"><h3>Ostatnie sprawdzenia healthcheck</h3>{state.Health.Log.slice(-3).reverse().map((l,i)=><div className="dc-health-log" key={i}><small>{dateText(l.End)} · kod {l.ExitCode}</small><pre>{l.Output||'Brak komunikatu'}</pre></div>)}</section>}
      <div className="dc-danger-zone"><span>Usunięcie kontenera usuwa też jego zapisywalną warstwę.</span><button className="btn danger" disabled={busy||['running','restarting','paused'].includes(c.state)} onClick={onRemove}>Usuń kontener</button>{['running','restarting','paused'].includes(c.state)&&<small>Najpierw zatrzymaj kontener.</small>}</div></>}
      {tab==='config'&&<><DockerResources key={c.id} c={c} raw={raw} onSaved={()=>{poll.refresh();onRefresh();}}/>
      <section className="dc-panel"><div className="dc-section-heading"><h3>Zmienne środowiskowe</h3><DCButton onClick={()=>setReveal(!reveal)}>{reveal?'Ukryj wartości':'Pokaż wartości'}</DCButton></div><div className="dc-env">{(raw.Config?.Env||[]).map((e,i)=>{const pos=e.indexOf('=');return <div key={i}><code>{pos<0?e:e.slice(0,pos)}</code><code>{reveal?e.slice(pos+1):'••••••••'}</code></div>;})}</div><p className="dc-muted">Zmiana zmiennych, obrazu i portów wymaga odtworzenia kontenera.{c.project&&<> Edytuj <button className="dc-link" onClick={onCompose}>projekt {c.project}</button>.</>}</p></section></>}
      {tab==='data'&&<section className="dc-panel"><h3>Dane aplikacji <small>{(raw.Mounts||[]).length} montowań</small></h3>{raw.Mounts?.length?<div className="dc-mounts">{raw.Mounts.map((m,i)=><div key={i}><div><span className="dc-tag">{m.Type}</span><span className="dc-tag">{m.RW?'Odczyt i zapis':'Tylko odczyt'}</span></div><dl className="dc-facts"><dt>Na hoście</dt><dd><code>{m.Source}</code></dd><dt>W kontenerze</dt><dd><code>{m.Destination}</code></dd>{m.Name&&<><dt>Wolumen</dt><dd>{m.Name}</dd></>}</dl></div>)}</div>:<DCEmpty title="Brak montowań">Dane zapisane w warstwie kontenera znikną po jego usunięciu.</DCEmpty>}</section>}
      {tab==='network'&&<div className="dc-two"><section className="dc-panel"><h3>Opublikowane porty</h3><DockerPorts ports={raw.NetworkSettings?.Ports}/></section><section className="dc-panel"><h3>Sieci kontenera</h3>{Object.entries(raw.NetworkSettings?.Networks||{}).map(([name,n])=><div className="dc-network" key={name}><strong>{name}</strong><dl className="dc-facts"><dt>IPv4</dt><dd>{n.IPAddress||'—'}</dd><dt>IPv6</dt><dd>{n.GlobalIPv6Address||'—'}</dd><dt>Brama</dt><dd>{n.Gateway||'—'}</dd><dt>MAC</dt><dd>{n.MacAddress||'—'}</dd></dl></div>)}</section></div>}
    </>}
  </div>;
}
function DockerAppLink({c}){
  if(c.state!=='running')return null;
  const matches=[...(c.ports||'').matchAll(/(0\.0\.0\.0|\[::\]|127\.0\.0\.1|[0-9.]+):(\d+)->(80|443|8080|8443|8096|8920|3000|9000|9090)\/tcp/g)];
  const binding=matches.find(m=>m[1]==='0.0.0.0'||m[1]==='[::]')||matches[0];
  if(!binding)return null;const host=['0.0.0.0','[::]'].includes(binding[1])?location.hostname:binding[1];
  if(host==='127.0.0.1'&&!['localhost','127.0.0.1'].includes(location.hostname))return null;
  const address=host.includes(':')&&!host.startsWith('[')?`[${host}]`:host;
  return <a className="dc-link dc-open-app" target="_blank" rel="noopener noreferrer" href={`${['443','8443','8920'].includes(binding[3])?'https':'http'}://${address}:${binding[2]}`}>Otwórz aplikację ↗</a>;
}
function DockerPorts({ports}){return Object.keys(ports||{}).length?Object.entries(ports).map(([target,bindings])=><div className="dc-network" key={target}><strong>{target}</strong>{bindings?.length?bindings.map((b,i)=>{const wildcard=['0.0.0.0','::',''].includes(b.HostIp);const host=wildcard?location.hostname:b.HostIp;const address=host.includes(':')&&!host.startsWith('[')?`[${host}]`:host;const web=!(host==='127.0.0.1'&&!['127.0.0.1','localhost'].includes(location.hostname))&&target.endsWith('/tcp')&&/^(80|443|8080|8443|8096|8920|3000|9000|9090)\//.test(target);return <p key={i}><code>{b.HostIp||'*'}:{b.HostPort}</code> → {target}{web&&<a className="dc-link" href={`${/^(443|8443|8920)\//.test(target)?'https':'http'}://${address}:${b.HostPort}`} target="_blank" rel="noopener noreferrer"> Otwórz ↗</a>}</p>;}):<p className="dc-muted">Dostępny tylko wewnątrz sieci Dockera</p>}</div>):<p className="dc-muted">Brak portów. Tryb host korzysta bezpośrednio z sieci hosta.</p>;}
function DockerResources({c,raw,onSaved}){
  const [restart,setRestart]=useState(raw.HostConfig?.RestartPolicy?.Name||'no'),[memory,setMemory]=useState(raw.HostConfig?.Memory?Math.round(raw.HostConfig.Memory/1048576):0),[cpus,setCpus]=useState(raw.HostConfig?.NanoCpus?raw.HostConfig.NanoCpus/1e9:raw.HostConfig?.CpuQuota>0?raw.HostConfig.CpuQuota/(raw.HostConfig.CpuPeriod||100000):0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');setSaved(false);try{await dockerAPI(`/services/docker/container/${encodeURIComponent(c.id)}/config`,{method:'PUT',body:JSON.stringify({restart,memory_mib:Number(memory),cpus:Number(cpus)})});setSaved(true);onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <form className="dc-panel" onSubmit={submit}><h3>Zasoby i ponowne uruchamianie</h3><DCError>{error}</DCError>{c.project&&<p className="dc-muted">Zmiany dotyczą obecnego kontenera. Zapisz je także w Compose, aby zachować je po kolejnym wdrożeniu.</p>}<div className="dc-form-grid"><label>Polityka restartu<select value={restart} onChange={e=>setRestart(e.target.value)}>{['no','unless-stopped','always','on-failure'].map(v=><option key={v}>{v}</option>)}</select></label><label>Limit pamięci (MiB)<input type="number" min="0" max="10485760" value={memory} onChange={e=>setMemory(e.target.value)} required/><small>0 = bez limitu; minimum 6 MiB. Swap: 2 × RAM.</small></label><label>Limit CPU (rdzenie)<input type="number" min="0" max="4096" step="0.1" value={cpus} onChange={e=>setCpus(e.target.value)} required/><small>0 = bez limitu</small></label></div><div className="dc-actions"><button type="submit" className="btn primary" disabled={busy}>{busy?'Zapisywanie…':'Zapisz konfigurację'}</button>{saved&&<span className="dc-success" role="status">Docker potwierdził zmianę.</span>}</div></form>;
}
function DockerLogs({id}){
  const [paused,setPaused]=useState(false),[query,setQuery]=useState(''),[tail,setTail]=useState('500'),[follow,setFollow]=useState(true);const poll=useDockerPoll(`/services/docker/container/logs/${encodeURIComponent(id)}?tail=${tail}`,paused?0:3000);const ref=useRef();
  const lines=poll.data?.logs||[];const filtered=lines.filter(l=>l.toLowerCase().includes(query.toLowerCase()));
  useEffect(()=>{if(follow&&ref.current)ref.current.scrollTop=ref.current.scrollHeight;},[poll.data,follow,query]);
  const download=()=>{const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`docker-${id}.log`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="dc-panel"><div className="dc-toolbar"><label className="dc-search"><DI name="search" size={16}/><input aria-label="Szukaj w logach" placeholder="Filtruj logi…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Liczba linii" value={tail} onChange={e=>setTail(e.target.value)}>{['100','500','2000','5000'].map(n=><option key={n} value={n}>{n} linii</option>)}</select><DCButton onClick={()=>setPaused(!paused)} icon={paused?'play':'pause'}>{paused?'Wznów':'Pauza'}</DCButton><DCButton icon="download" disabled={!poll.data} onClick={download}>Pobierz</DCButton></div><DCError>{poll.error}</DCError><div className="dc-log-meta"><span>{paused?'Odświeżanie wstrzymane':'Odświeżanie co 3 s'} · {filtered.length} linii</span><label><input type="checkbox" checked={follow} onChange={e=>setFollow(e.target.checked)}/> Przewijaj do końca</label></div><pre className="dc-log" ref={ref}>{filtered.join('\n')||(poll.loading?'Pobieranie logów…':query?'Brak pasujących wpisów.':'Brak logów.')}</pre></section>;
}
let dockerTermAssets;
function loadDockerTerminal(){if(!dockerTermAssets)dockerTermAssets=(async()=>{const base='https://cdn.jsdelivr.net/npm/';if(!document.querySelector('[data-docker-xterm]')){const l=document.createElement('link');l.rel='stylesheet';l.href=base+'xterm@5.3.0/css/xterm.css';l.dataset.dockerXterm='true';document.head.append(l);}for(const [present,path] of [[()=>window.Terminal,'xterm@5.3.0/lib/xterm.js'],[()=>window.FitAddon,'@xterm/addon-fit@0.10.0/lib/addon-fit.js']]){if(!present())await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=base+path;s.onload=resolve;s.onerror=()=>reject(new Error('Nie udało się załadować terminala z CDN.'));document.head.append(s);});}})().catch(e=>{dockerTermAssets=null;throw e;});return dockerTermAssets;}
function DockerTerminal({id}){
  const ref=useRef(),[shell,setShell]=useState('/bin/sh'),[attempt,setAttempt]=useState(0),[status,setStatus]=useState('Łączenie…'),[error,setError]=useState('');
  useEffect(()=>{let disposed=false,term,ws,observer;setStatus('Łączenie…');setError('');(async()=>{try{await loadDockerTerminal();if(disposed)return;term=new window.Terminal({cursorBlink:true,fontSize:13,fontFamily:'monospace',theme:{background:'#10151e',foreground:'#e4eaf4'}});const fit=new window.FitAddon.FitAddon();term.loadAddon(fit);term.open(ref.current);fit.fit();ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/terminal/ws?container=${encodeURIComponent(id)}&shell=${encodeURIComponent(shell)}&cols=${term.cols}&rows=${term.rows}`);ws.binaryType='arraybuffer';ws.onopen=()=>{setStatus('Połączono');term.focus();};ws.onmessage=e=>term.write(typeof e.data==='string'?e.data:new Uint8Array(e.data));ws.onerror=()=>setError('Nie udało się połączyć z terminalem kontenera.');ws.onclose=()=>!disposed&&setStatus('Rozłączono');term.onData(data=>{if(ws.readyState===1)ws.send('0'+data);});observer=new ResizeObserver(()=>{fit.fit();if(ws.readyState===1){const buf=new Uint8Array(5);buf[0]=49;const v=new DataView(buf.buffer);v.setUint16(1,term.cols,true);v.setUint16(3,term.rows,true);ws.send(buf);}});observer.observe(ref.current);}catch(e){if(!disposed){setError(e.message);setStatus('Błąd');}}})();return()=>{disposed=true;observer?.disconnect();ws?.close();term?.dispose();};},[id,shell,attempt]);
  return <section className="dc-panel"><div className="dc-section-heading"><h3>Terminal kontenera <small>{status}</small></h3><div className="dc-actions"><select aria-label="Powłoka" value={shell} onChange={e=>setShell(e.target.value)}><option>/bin/sh</option><option>/bin/bash</option></select><DCButton onClick={()=>setAttempt(a=>a+1)}>Połącz ponownie</DCButton></div></div><DCError>{error}</DCError><div className="dc-terminal" ref={ref}/><p className="dc-muted">Interaktywna sesja wewnątrz kontenera. Powłoka musi być dostępna w obrazie.</p></section>;
}
function DockerProjects({onChanged}){
  const poll=useDockerPoll('/services/docker/compose',0);const [edit,setEdit]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[output,setOutput]=useState('');
  const open=async p=>{setError('');setBusy(p.file);try{const d=await dockerAPI('/api/docker/compose-file?path='+encodeURIComponent(p.file));setEdit({...p,original:d.content||'',content:d.content||''});}catch(e){setError(e.message);}finally{setBusy('');}};
  const action=async(p,action)=>{setBusy(p.file);setError('');setOutput('');try{const d=await dockerAPI('/api/docker/workspace/compose',{method:'POST',body:JSON.stringify({name:p.name,file:p.file,action})});setOutput(d.output||'Docker Compose potwierdził wykonanie.');await poll.refresh();onChanged();}catch(e){setError(e.message);}finally{setBusy('');}};
  if(edit)return <DockerComposeEditor initial={edit} onBack={()=>setEdit(null)} onSaved={()=>{poll.refresh();onChanged();}}/>;
  return <><div className="dc-section-heading"><div><h2>Projekty Compose</h2><p className="dc-muted">Konfiguracja i wspólny cykl życia aplikacji.</p></div><div className="dc-actions"><DCButton icon="refresh" disabled={poll.loading} onClick={poll.refresh}>Odśwież projekty</DCButton><button className="btn primary" onClick={()=>setEdit({name:'',file:'',original:'',content:'services:\n  app:\n    image: nginx:alpine\n    restart: unless-stopped\n    ports:\n      - "8080:80"\n'})}>Nowy projekt</button></div></div><DCError>{error||poll.error}</DCError>{output&&<pre className="dc-command-output">{output}</pre>}{poll.loading&&!poll.data?<DCEmpty title="Odczytywanie projektów…"/>:!poll.data?.stacks?.length?<DCEmpty title="Brak projektów Compose">Utwórz projekt lub zainstaluj aplikację z szablonu.</DCEmpty>:<div className="dc-projects">{poll.data.stacks.map(p=><section className="dc-panel" key={p.file}><div className="dc-section-heading"><h3><DI name="folder" size={19}/> {p.name}</h3><DCStatus c={p}/></div><code className="dc-project-path">{p.file}</code><div className="dc-service-tags">{p.services?.map(v=><span className="dc-tag" key={v}>{v}</span>)}</div><DCError>{p.error}</DCError><div className="dc-actions"><DCButton icon="edit" disabled={!!busy||p.file.includes(',')} onClick={()=>open(p)}>Edytuj YAML</DCButton><DCButton icon={p.status==='running'?'stop':'play'} disabled={!!busy} onClick={()=>action(p,p.status==='running'?'stop':'up')}>{busy===p.file?'Trwa operacja…':p.status==='running'?'Zatrzymaj':'Wdróż'}</DCButton></div>{p.file.includes(',')&&<small className="dc-muted">Projekt z kilkoma plikami — edycja na hoście.</small>}</section>)}</div>}</>;
}
function DockerComposeEditor({initial,onBack,onSaved}){
  const [name,setName]=useState(initial.name),[file,setFile]=useState(initial.file),[content,setContent]=useState(initial.content),[original,setOriginal]=useState(initial.original),[diff,setDiff]=useState(false),[phase,setPhase]=useState(''),[error,setError]=useState(''),[result,setResult]=useState('');
  const run=async(action)=>{setError('');setResult('');setPhase('Walidacja konfiguracji…');const body={name,file,content};try{await dockerAPI('/api/docker/workspace/compose',{method:'POST',body:JSON.stringify({...body,action:'validate'})});if(action==='validate'){setResult('Konfiguracja jest poprawna.');return;}setPhase(action==='deploy'?'Zapisywanie i wdrażanie projektu…':'Zapisywanie konfiguracji…');const d=await dockerAPI('/api/docker/workspace/compose',{method:'POST',body:JSON.stringify({...body,action})});setFile(d.file);setOriginal(content);setResult(d.output||(action==='save'?'Zapisano konfigurację.':'Docker Compose potwierdził wdrożenie.'));onSaved();}catch(e){if(e.data?.saved){setFile(e.data.file);setOriginal(content);onSaved();}setError(e.data?.saved?'Plik zapisano, ale wdrożenie nie powiodło się. '+e.message:e.message);}finally{setPhase('');}};
  return <div className="dc-compose-editor"><button className="dc-back" disabled={!!phase} onClick={onBack}>← Projekty Compose</button><div className="dc-section-heading"><h2>{initial.file?'Edycja projektu':'Nowy projekt'}</h2><DCButton disabled={!!phase} onClick={()=>setDiff(!diff)}>{diff?'Edytor YAML':'Podgląd zmian'}</DCButton></div><label className="dc-project-name">Nazwa projektu<input value={name} disabled={!!file||!!phase} onChange={e=>setName(e.target.value)} placeholder="np. media" pattern="[a-z0-9][a-z0-9_.-]*"/></label>{file&&<p className="dc-project-path">{file}</p>}<DCError>{error}</DCError>{diff?<div className="dc-diff"><section><h3>Przed zmianą</h3><pre>{original||'Nowy plik'}</pre></section><section><h3>Po zmianie</h3><pre>{content}</pre></section></div>:<textarea className="dc-yaml" aria-label="Konfiguracja Compose YAML" spellCheck="false" value={content} disabled={!!phase} onChange={e=>{setContent(e.target.value);setResult('');}}/>}<div className="dc-editor-footer"><span className="dc-muted">{content===original?'Brak niezapisanych zmian':'Niezapisane zmiany'} · plik YAML</span><div className="dc-actions"><DCButton disabled={!!phase||!name} onClick={()=>run('validate')}>Sprawdź YAML</DCButton><DCButton disabled={!!phase||!name} onClick={()=>run('save')}>Zapisz</DCButton><button className="btn primary" disabled={!!phase||!name} onClick={()=>run('deploy')}>Zapisz i wdróż</button></div></div>{phase&&<div className="dc-progress" role="status"><span className="dc-spinner"/>{phase}<small>Oczekiwanie na wynik Docker Compose</small></div>}{result&&<pre className="dc-command-output" role="status">{result}</pre>}</div>;
}
window.Docker=DockerWorkspace;
