// Download workspace. Unit-aware values; daemon and KVM actions stay distinct.
const dlwNumber=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?Number(v):null;
const dlwBytes=n=>dlwNumber(n)===null?'—':n>=1e9?(n/1e9).toFixed(1)+' GB':n>=1e6?(n/1e6).toFixed(1)+' MB':(n/1e3).toFixed(1)+' kB';
function dlwRate(v){
 if(typeof v!=='string')return null;
 const match=v.trim().replace(',','.').match(/^([\d.]+)\s*([KMGT]?i?B)\s*\/s$/i);if(!match)return null;
 const unit=match[2].toUpperCase(),prefix=unit[0],power=({K:1,M:2,G:3,T:4})[prefix]||0;
 return Number(match[1])*Math.pow(unit.includes('I')?1024:1000,power);
}
const dlwStatus=t=>t.status||t.state||'unknown';
const dlwComplete=t=>['done','completed'].includes(dlwStatus(t));
const dlwState=s=>({downloading:'Pobieranie',running:'Wdrażanie',queued:'W kolejce',paused:'Wstrzymane',done:'Gotowe',completed:'Gotowe',error:'Błąd',cancelled:'Anulowane',seeding:'Udostępnianie'})[s]||'Nieznany';
const dlwTone=s=>s==='error'?'error':['done','completed','seeding'].includes(s)?'ok':['downloading','running'].includes(s)?'active':'muted';
const dlwName=t=>t.filename||t.name||t.id;
const dlwKey=t=>(t._kvm?'kvm:':t.source?'external:'+t.source+':':'download:')+t.id;
const dlwActions=t=>t._kvm||t.source?[]:['downloading','queued'].includes(dlwStatus(t))?['cancel']:['error','cancelled'].includes(dlwStatus(t))?['retry','delete']:dlwComplete(t)?['delete']:[];
const dlwImportable=t=>!t._kvm&&!t.source&&dlwComplete(t)&&/\.qcow2(?:\.zip)?$/i.test(dlwName(t));
function DownloadWorkspace({tasks,loading,stale,busy,freeBytes,spaceDir,defaultDir,setDefaultDir,onRefresh,onCancel,onDelete,onRetry,onClearDone,showArrQueue,onToggleArrQueue,request,post}){
 const [search,setSearch]=React.useState(''),[filter,setFilter]=React.useState('all'),[selected,setSelected]=React.useState(''),[adding,setAdding]=React.useState(false),[url,setURL]=React.useState(''),[filename,setFilename]=React.useState(''),[error,setError]=React.useState(''),[saving,setSaving]=React.useState(false),[notice,setNotice]=React.useState('');
 const [jobs,setJobs]=React.useState([]),[jobsError,setJobsError]=React.useState(''),[importing,setImporting]=React.useState(null),[form,setForm]=React.useState({name:'',cpu:2,ram:2048,disk:40,network:'default'}),[confirm,setConfirm]=React.useState(null);
 const confirmRef=React.useRef(null);React.useEffect(()=>{if(confirm&&confirmRef.current){const previous=document.activeElement;confirmRef.current.showModal();return()=>{confirmRef.current?.close();previous?.focus()}}},[confirm]);
 const poll=React.useCallback(async()=>{try{const d=await request('/api/kvm/template-jobs');if(!Array.isArray(d.jobs))throw Error('Brak listy wdrożeń KVM');return d.jobs}catch(e){throw e}},[request]);
 React.useEffect(()=>{let alive=true,timer;const tick=async()=>{try{const list=await poll();if(alive){setJobs(list);setJobsError('')}}catch(e){if(alive)setJobsError(e.message)}finally{if(alive)timer=setTimeout(tick,4000)}};tick();return()=>{alive=false;clearTimeout(timer)}},[poll]);
 const combined=[...tasks,...jobs.map(j=>({...j,_kvm:true,filename:j.name,category:'kvm'}))];
 const list=combined.filter(t=>(filter==='all'||filter==='active'&&['downloading','running','queued','seeding'].includes(dlwStatus(t))||filter==='error'&&dlwStatus(t)==='error'||filter==='done'&&dlwComplete(t)||filter==='kvm'&&t._kvm)&&[dlwName(t),t.url,t.category].join(' ').toLowerCase().includes(search.toLowerCase()));
 const chosen=list.find(t=>dlwKey(t)===selected)||list[0];
 const rates=tasks.filter(t=>dlwStatus(t)==='downloading').map(t=>dlwRate(t.speed));
 const totalRate=stale||rates.some(v=>v===null)?null:rates.reduce((a,b)=>a+b,0);
 const actionLabels={cancel:'Anuluj pobieranie',retry:'Ponów',delete:'Usuń z historii'};
 const execute=async(kind,task)=>{setConfirm(null);await ({cancel:onCancel,retry:onRetry,delete:onDelete})[kind](task.id)};
 const add=async e=>{e.preventDefault();if(saving)return;setSaving(true);setError('');setNotice('');try{await post('/api/downloads/add',{url:url.trim(),filename:filename.trim(),dest_dir:defaultDir});setAdding(false);setURL('');setFilename('');setNotice('Dodano pobieranie do kolejki.');onRefresh()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const openImport=t=>{setImporting(t);setError('');setForm({name:dlwName(t).replace(/\.qcow2(?:\.zip)?$/i,'').replace(/[^a-zA-Z0-9_.-]/g,'-').slice(0,50)+'-vm',cpu:2,ram:2048,disk:40,network:'default'})};
 const deploy=async e=>{e.preventDefault();if(saving)return;setSaving(true);setError('');try{const d=await post('/api/kvm/template-deploy',{downloadID:importing.id,...form});setNotice('Przyjęto import KVM. Postęp znajdziesz na liście wdrożeń.');setSelected('kvm:'+d.job_id);setFilter('kvm');setImporting(null);try{setJobs(await poll());setJobsError('')}catch(e){setJobsError(e.message)}}catch(e){setError(e.message)}finally{setSaving(false)}};
 const openKVM=()=>{window.__nimbusKVMTab='templates';location.hash='kvm'};
 const Status=({task})=><span className={'dlw-status '+dlwTone(dlwStatus(task))}><i/>{dlwState(dlwStatus(task))}</span>;
 return <div className="dlw nimbus-paper">
  <header className="dlw-heading"><div><span>CENTRUM POBIERANIA</span><h2>Pobieranie</h2><p>Pobieranie, obrazy systemów i wdrożenia maszyn.</p></div><button className="btn primary" onClick={()=>{setAdding(!adding);setError('')}}><window.Icon name="plus" size={16}/> Dodaj pobieranie</button></header>
  <div className="dlw-summary">{[['Prędkość pobierania',loading?'—':totalRate===null?'Brak pomiaru':dlwBytes(totalRate)+'/s','Suma raportowana przez klientów'],['Aktywne zadania',loading?'—':combined.filter(t=>['downloading','running','queued'].includes(dlwStatus(t))).length,'Pobieranie i wdrażanie KVM'],['Wolne miejsce',stale?'—':dlwBytes(freeBytes),spaceDir||'Katalog domyślny nimbus-dl'],['Wymagają uwagi',combined.filter(t=>dlwStatus(t)==='error').length,'Błędy pobierania lub importu']].map(([name,value,sub])=><div key={name}><span>{name}</span><strong>{value}</strong><small title={sub}>{sub}</small></div>)}</div>
  {notice&&<div className="dlw-notice" role="status">{notice}</div>}{jobsError&&<div className="dlw-error" role="status">Odczyt wdrożeń KVM: {jobsError}</div>}
  {adding&&<form className="dlw-form" onSubmit={add}><h3>Nowe pobieranie</h3><label>Adres URL lub magnet<input autoFocus value={url} onChange={e=>setURL(e.target.value)} required placeholder="https://…"/></label><div className="dlw-form-grid"><label>Nazwa pliku (opcjonalnie)<input value={filename} onChange={e=>setFilename(e.target.value)}/></label><label>Katalog docelowy<input value={defaultDir} onChange={e=>setDefaultDir(e.target.value)} required/></label></div>{error&&<div className="dlw-error" role="alert">{error}</div>}<div className="dlw-actions"><button type="button" className="btn" onClick={()=>setAdding(false)} disabled={saving}>Zamknij</button><button className="btn primary" disabled={saving||!url.trim()}>{saving?'Dodawanie…':'Dodaj do kolejki'}</button></div></form>}
  {importing&&<form className="dlw-form" onSubmit={deploy}><h3>Utwórz VM z {dlwName(importing)}</h3><p>Oryginalny plik pozostanie w Download Center. Nimbus przygotuje kopię w katalogu obrazów KVM.</p><div className="dlw-form-grid">{[['name','Nazwa VM','text'],['network','Sieć libvirt','text'],['cpu','vCPU','number'],['ram','RAM (MiB)','number'],['disk','Dysk (GiB)','number']].map(([key,label,type])=><label key={key}>{label}<input required type={type} min={type==='number'?1:undefined} value={form[key]} onChange={e=>setForm(f=>({...f,[key]:type==='number'?Number(e.target.value):e.target.value}))}/></label>)}</div>{error&&<div className="dlw-error" role="alert">{error}</div>}<div className="dlw-actions"><button type="button" className="btn" onClick={()=>setImporting(null)} disabled={saving}>Anuluj</button><button className="btn primary" disabled={saving}>{saving?'Przygotowanie…':'Importuj i uruchom VM'}</button></div></form>}
  <div className="dlw-workspace"><section className="dlw-list-panel"><div className="dlw-toolbar"><div className="dlw-filters" aria-label="Filtr pobrań">{[['all','Wszystkie'],['active','Aktywne'],['done','Gotowe'],['error','Błędy'],['kvm','Wdrożenia KVM']].map(([key,label])=><button key={key} className={filter===key?'selected':''} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div><input aria-label="Szukaj pobrania" placeholder="Szukaj pliku…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
   <div className="dlw-list">{list.map(t=>{const pct=dlwNumber(t.progress),state=dlwStatus(t);return <button key={dlwKey(t)} className={'dlw-row '+(chosen&&dlwKey(chosen)===dlwKey(t)?'selected':'')} onClick={()=>setSelected(dlwKey(t))} aria-pressed={chosen&&dlwKey(chosen)===dlwKey(t)}><span className={'dlw-file-icon '+dlwTone(state)}><window.Icon name={t._kvm?'hdd':/qcow|iso/i.test(dlwName(t))?'disk':'download'} size={23}/></span><div><div className="dlw-row-title"><strong>{dlwName(t)}</strong><Status task={t}/></div><p>{t._kvm?t.step:t.source?'Klient: '+t.source:(t.category||'HTTP')+' · '+(t.dest_dir||defaultDir)}</p><div className={'dlw-progress '+dlwTone(state)}><i style={{width:Math.max(0,Math.min(100,pct||0))+'%'}}/></div><div className="dlw-row-meta"><span>{pct===null?'Rozmiar nieznany':pct.toFixed(1)+'%'} {t.size_done&&'· '+t.size_done}{t.size_total&&' / '+t.size_total}</span><span>{t._kvm?'Etap wdrożenia':t.speed||'—'} {t.eta&&'· '+t.eta}</span></div>{t.error&&<div className="dlw-task-error">{t.error}</div>}</div><span className="dlw-chevron">›</span></button>})}{!list.length&&<div className="dlw-empty"><window.Icon name="download" size={34}/><h3>{loading?'Ładowanie kolejki…':'Brak pasujących zadań'}</h3><p>Dodaj adres pliku lub zmień filtr.</p></div>}</div>
   <footer className="dlw-list-footer"><label><input type="checkbox" checked={showArrQueue} onChange={onToggleArrQueue}/> Pokaż klientów zewnętrznych</label><button className="btn sm" onClick={onRefresh}>Odśwież</button><button className="btn sm" disabled={!!busy||!tasks.some(dlwComplete)} onClick={()=>setConfirm({clear:true})}>Wyczyść zakończone</button></footer>
  </section><aside className="dlw-inspector"><span>SZCZEGÓŁY ZADANIA</span>{chosen?<><div className="dlw-detail-title"><window.Icon name={chosen._kvm?'hdd':'download'} size={30}/><h3>{dlwName(chosen)}</h3><Status task={chosen}/></div><dl>{[['Źródło',chosen._kvm?'KVM · '+chosen.template:chosen.url||chosen.source||'—'],['Katalog / obraz',chosen.image_path||chosen.dest_dir||'—'],['Etap',chosen.step||dlwState(dlwStatus(chosen))],['Rozmiar',chosen.size_total||'—'],['Pobrano',chosen.size_done||'—'],['Pozostały czas',chosen.eta||'Brak pomiaru'],['Utworzono',chosen.created_at||chosen.started||'—'],['Ukończono',chosen.done_at||'—']].map(([label,value])=><React.Fragment key={label}><dt>{label}</dt><dd>{value}</dd></React.Fragment>)}</dl>{chosen.error&&<div className="dlw-error" role="alert"><strong>{chosen.step||'Operacja nie powiodła się'}</strong><p>{chosen.error}</p></div>}
    <div className="dlw-actions">{dlwActions(chosen).map(kind=><button key={kind} className={'btn '+(kind==='retry'?'primary':'')} disabled={!!busy||stale} onClick={()=>kind==='retry'?execute(kind,chosen):setConfirm({kind,task:chosen})}>{busy===chosen.id?'Wykonywanie…':actionLabels[kind]}</button>)}{dlwImportable(chosen)&&<button className="btn primary" disabled={stale} onClick={()=>openImport(chosen)}>Utwórz maszynę KVM</button>}{chosen._kvm&&<button className="btn" onClick={openKVM}>Otwórz wdrożenia KVM →</button>}</div><p className="dlw-capability">{chosen.source?'Sterowanie tym zadaniem odbywa się w kliencie '+chosen.source+'.':chosen._kvm?'Pasek pokazuje postęp całego wdrożenia. Szczegóły pobierania i rozpakowania pojawiają się w opisie etapu.':'Ten klient obsługuje anulowanie i ponowienie. Pauza i wznowienie nie są dostępne w jego API.'}</p></>:<div className="dlw-empty">Wybierz pobranie z listy.</div>}</aside></div>
  {confirm&&<dialog ref={confirmRef} className="dlw-confirm" aria-label="Potwierdź operację" onCancel={()=>setConfirm(null)}><p>{confirm.clear?'Usunąć zakończone zadania z historii?':confirm.kind==='cancel'?'Anulować pobieranie? Klient może usunąć częściowo pobrany plik.':'Usunąć wpis z historii? Plik pozostanie na dysku.'}</p><div className="dlw-actions"><button className="btn" onClick={()=>setConfirm(null)}>Wróć</button><button className="btn danger" disabled={!!busy} onClick={()=>{if(confirm.clear){setConfirm(null);onClearDone()}else execute(confirm.kind,confirm.task)}}>Potwierdź</button></div></dialog>}
 </div>;
}
window.DownloadWorkspace=DownloadWorkspace;
window.DownloadWorkspaceHelpers={dlwRate,dlwActions,dlwImportable,dlwKey,dlwNumber};
