// Network workspace: all interfaces, physical-only totals, confirmed mutations.
const netKind = i => i.kind || 'virtual';
const netRate = value => Number.isFinite(value) ? (value < 1 ? (value*1000).toFixed(1)+' kB/s' : value.toFixed(2)+' MB/s') : '—';
const netSpeed = i => i.physical && !i.carrier ? 'Brak linku' : Number(i.speed_mbps)>0 ? (i.speed_mbps>=1000 ? (i.speed_mbps/1000)+' Gb/s' : i.speed_mbps+' Mb/s') : '—';
const netState = i => !i.admin_up ? 'Wyłączony' : i.state==='up' ? 'Połączony' : i.state==='no-carrier' ? 'Brak linku' : 'Nieznany';
async function networkRequest(path, body, signal) {
 const ctrl=new AbortController();let timedOut=false;
 const abort=()=>ctrl.abort();if(signal?.aborted)abort();else signal?.addEventListener('abort',abort,{once:true});
 const timer=setTimeout(()=>{timedOut=true;ctrl.abort()},body?30000:10000);
 try {
  const r=await fetch(path,{credentials:'include',signal:ctrl.signal,...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});
  let d;try{d=await r.json()}catch(e){if(ctrl.signal.aborted)throw e;throw Error('HTTP '+r.status+' — nieprawidłowa odpowiedź serwera')};
  if(!r.ok || d.error || d.status==='error') throw Error(d.error||d.message||'Błąd operacji sieciowej');return d;
 } catch(e) {
  if(timedOut)throw Error(body?'Brak odpowiedzi przez 30 sekund. Wynik zmiany jest nieznany — sprawdź połączenie i aktualny stan, zanim ponowisz operację.':'Brak odpowiedzi serwera przez 10 sekund.');
  throw e;
 } finally {clearTimeout(timer);signal?.removeEventListener('abort',abort)}
}
const NetworkWorkspace = ({onAdvanced}) => {
 const [ifaces,setIfaces]=React.useState([]),[selected,setSelected]=React.useState(''),[filter,setFilter]=React.useState('all'),[search,setSearch]=React.useState('');
 const [series,setSeries]=React.useState({}),[error,setError]=React.useState(''),[loaded,setLoaded]=React.useState(false),[updated,setUpdated]=React.useState(null);
 const [pending,setPending]=React.useState(null),[busy,setBusy]=React.useState(false),[detail,setDetail]=React.useState('overview'),[diagnostic,setDiagnostic]=React.useState(''),[clock,setClock]=React.useState(Date.now());
 const [edit,setEdit]=React.useState(null),[value,setValue]=React.useState('');
 const [pollError,setPollError]=React.useState('');
 const [started,setStarted]=React.useState(0),[notice,setNotice]=React.useState('');
 const kinds={all:'Wszystkie',physical:'Fizyczne',bridge:'Bridge',bond:'Bond',vlan:'VLAN',virtual:'Wirtualne'};
 const refresh=React.useCallback(async(signal)=>{
  const [inventory,bandwidth,changes]=await Promise.all([networkRequest('/network/interfaces',null,signal),networkRequest('/api/network/bandwidth',null,signal),networkRequest('/network/changes',null,signal)]);
  const list=inventory.interfaces||[];setIfaces(list);setSeries(Object.fromEntries((bandwidth.interfaces||[]).map(i=>[i.name,i])));setPending(changes.pending||null);
  setSelected(prev=>list.some(i=>i.name===prev)?prev:(list.find(i=>i.physical&&i.admin_up)||list[0])?.name||'');setLoaded(true);setUpdated(new Date());setPollError('');
 },[]);
 React.useEffect(()=>{
  const ctrl=new AbortController();let timer;
  const poll=async()=>{try{await refresh(ctrl.signal)}catch(e){if(e.name!=='AbortError'){setPollError(e.message);setLoaded(true)}}finally{if(!ctrl.signal.aborted)timer=setTimeout(poll,3000)}};
  poll();return()=>{ctrl.abort();clearTimeout(timer)};
 },[refresh]);
 React.useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer)},[]);
 React.useEffect(()=>{setDetail('overview');setDiagnostic('');setEdit(null)},[selected]);
 const iface=ifaces.find(i=>i.name===selected),physical=ifaces.filter(i=>i.physical);
 const last=(i,key)=>{const samples=series[i.name]?.[key];return samples?.length?samples[samples.length-1]:null};
 const total=key=>{const vals=physical.map(i=>last(i,key));return vals.length&&vals.every(Number.isFinite)?vals.reduce((a,b)=>a+b,0):null};
 const visible=ifaces.filter(i=>(filter==='all'||netKind(i)===filter)&&[i.name,...(i.addresses||[]),i.master].join(' ').toLowerCase().includes(search.toLowerCase()));
 const mutate=async body=>{
  setBusy(true);setStarted(Date.now());setError('');setNotice('');
  try {
   const d=await networkRequest('/network/changes',body);setPending(d.pending||null);setEdit(null);
   setNotice(d.pending?'Zmiana zastosowana — potwierdź działające połączenie w ciągu 90 sekund.':body.action==='revert'?'Konfiguracja została cofnięta.':'Zmiana została potwierdzona.');
   try{await refresh()}catch(e){setPollError('Operacja otrzymała odpowiedź, ale odświeżenie stanu nie powiodło się: '+e.message)}
  }catch(e){setError(e.message+' Nie ponawiam operacji automatycznie.');}finally{setBusy(false)}
 };
 const inspect=async()=>{setDetail('diagnostics');setBusy(true);setStarted(Date.now());setDiagnostic('');try{const d=await networkRequest('/network/interfaces/details/'+encodeURIComponent(selected));setDiagnostic([d.addr,d.stats].filter(Boolean).join('\n'))}catch(e){setError(e.message)}finally{setBusy(false)}};
 const openEdit=action=>{setEdit(action);setValue(action==='mtu'?String(iface.mtu):(iface.addresses||[]).find(a=>a.includes('.'))||'')};
 const changeAddress=()=>mutate({interface:selected,action:edit,...(edit==='mtu'?{mtu:Number(value)}:{address:value.trim(),old_address:(iface.addresses||[]).find(a=>a.includes('.'))||''})});
 const chart=series[selected]||{rx:[],tx:[]};
 return <div className="nw-workspace">
  <style>{`
   .nw-workspace{display:flex;flex-direction:column;gap:20px;min-width:0}.nw-workspace button{cursor:pointer}.nw-workspace button:disabled{cursor:wait;opacity:.5}.nw-workspace button:focus-visible,.nw-workspace input:focus-visible{outline:2px solid var(--accent);outline-offset:3px}
   .nw-heading,.nw-actions{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.nw-heading h2{font-size:25px;letter-spacing:-.7px;margin:0 0 6px}.nw-muted{color:var(--fg-dim);font-size:12px}.nw-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.nw-stat{padding:18px 20px;border:1px solid var(--line);border-radius:16px;background:var(--bg-1)}.nw-stat strong{display:block;font-size:24px;font-weight:600;margin:8px 0;letter-spacing:-.7px}
   .nw-chassis{padding:22px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(140deg,var(--bg-2),var(--bg-1));box-shadow:inset 0 1px 0 #ffffff0a}.nw-ports{display:flex;gap:18px;flex-wrap:wrap;margin-top:22px}.nw-port{min-width:98px;padding:14px;border:1px solid var(--line);border-radius:12px;color:var(--fg);background:var(--bg);text-align:center}.nw-port[aria-pressed=true]{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-soft)}.nw-socket{display:block;position:relative;width:55px;height:41px;margin:0 auto 10px;border:3px solid #687587;border-radius:4px;background:#101820;box-shadow:inset 0 0 0 3px #05090e}.nw-socket:before{content:'';position:absolute;top:6px;left:8px;right:8px;height:10px;background:repeating-linear-gradient(90deg,#af9664 0 2px,transparent 2px 5px)}.nw-led{position:absolute;right:-7px;bottom:-6px;width:8px;height:8px;border-radius:50%;background:#596272}.nw-led.on{background:var(--ok);box-shadow:0 0 9px var(--ok)}.nw-port small{display:block;margin-top:5px;font-size:10px;color:var(--fg-dim)}
   .nw-layout{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(300px,1fr);gap:20px;align-items:start}.nw-panel{border:1px solid var(--line);border-radius:18px;background:var(--bg-1);min-width:0;overflow:hidden}.nw-panel-head{padding:18px 20px;border-bottom:1px solid var(--line)}.nw-search{width:100%;padding:10px 13px;color:var(--fg);border:1px solid var(--line);background:var(--bg);border-radius:10px;margin:14px 0}.nw-filters{display:flex;gap:6px;flex-wrap:wrap}.nw-filters button{font-size:11px;padding:6px 10px;border:0;background:transparent;color:var(--fg-dim);border-radius:7px}.nw-filters button.active{background:var(--accent-soft);color:var(--accent)}
   .nw-row{display:grid;grid-template-columns:36px minmax(0,1fr) auto;align-items:center;gap:12px;text-align:left;width:100%;padding:17px 20px;background:transparent;color:var(--fg);border:0;border-bottom:1px solid var(--line)}.nw-row[aria-pressed=true]{background:var(--accent-soft);box-shadow:inset 3px 0 var(--accent)}.nw-row strong{display:block;margin-bottom:5px}.nw-symbol{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;background:var(--bg-3);color:var(--accent);font-size:18px}.nw-row small{display:block;color:var(--fg-dim);margin-top:5px;overflow-wrap:anywhere}.nw-status{font-size:11px}.nw-status.up{color:var(--ok)}.nw-status.no-carrier{color:var(--warn)}.nw-detail-body{padding:20px}.nw-kv{display:flex;justify-content:space-between;gap:20px;padding:10px 0;border-bottom:1px solid var(--line);font-size:12px}.nw-kv span{color:var(--fg-dim)}.nw-kv b{text-align:right;font-weight:500;overflow-wrap:anywhere;min-width:0}.nw-alert{border:1px solid var(--warn);background:var(--bg-2);padding:16px 20px;border-radius:14px}.nw-alert.error{border-color:var(--err);color:var(--err)}.nw-empty{padding:35px;text-align:center;color:var(--fg-dim)}.nw-workspace pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px;max-height:420px;overflow:auto}.nw-edit label{display:block;margin:12px 0}.nw-edit input{display:block;width:100%;margin:8px 0;padding:10px;border-radius:8px;background:var(--bg);color:var(--fg);border:1px solid var(--line)}
   @media(max-width:1050px){.nw-layout{grid-template-columns:1fr}.nw-summary{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:540px){.nw-summary{grid-template-columns:1fr}.nw-row{padding:14px 12px;grid-template-columns:25px minmax(0,1fr) auto}.nw-port{min-width:80px}.nw-chassis{padding:16px}.nw-row .nw-rate{display:none}}
  `}</style>
  <div className="nw-heading"><div><h2>Twoja sieć</h2><div className="nw-muted">Połączenia, interfejsy i ruch serwera w jednym miejscu</div></div><div className="nw-muted">{updated?'Odczyt '+updated.toLocaleTimeString('pl-PL'):'Oczekiwanie na dane'}</div></div>
  {busy&&<div className="nw-alert" role="status" aria-live="polite">Oczekiwanie na wynik operacji… {Math.max(0,Math.floor((clock-started)/1000))} s. Zmiana IP lub wyłączenie karty może przerwać połączenie z panelem.</div>}
  {notice&&<div className="nw-alert" role="status">{notice}</div>}
  {pollError&&<div className="nw-alert error" role="alert">Odczyt nieudany: {pollError}. Wyświetlane dane mogą być nieaktualne.</div>}
  {error&&<div className="nw-alert error" role="alert">{error}</div>}
  {pending&&<div className="nw-alert" role="status"><strong>{pending.error?'Cofanie wymaga uwagi':'Sprawdź połączenie · '+pending.interface}</strong><p>{pending.error||'Potwierdź dostęp do panelu. Niepotwierdzona zmiana zostanie cofnięta za '+Math.max(0,Math.ceil((Date.parse(pending.deadline)-clock)/1000))+' s.'}</p><div className="nw-actions"><button className="btn primary" disabled={busy||!!pending.error||Date.parse(pending.deadline)<=clock} onClick={()=>mutate({action:'confirm',id:pending.id})}>Połączenie działa — zachowaj</button><button className="btn" disabled={busy} onClick={()=>mutate({action:'revert',id:pending.id})}>Cofnij teraz</button></div></div>}
  <div className="nw-summary">{[['Porty połączone',physical.filter(i=>i.carrier).length+' / '+physical.length,'Karty fizyczne'],['Odbieranie',netRate(total('rx')),'Suma portów fizycznych'],['Wysyłanie',netRate(total('tx')),'Bez podwójnego liczenia bridge'],['Interfejsy',String(ifaces.length),'Fizyczne i wirtualne']].map(([title,val,sub])=><div className="nw-stat" key={title}><span className="nw-muted">{title}</span><strong>{loaded?val:'—'}</strong><span className="nw-muted">{sub}</span></div>)}</div>
  <div className="nw-chassis"><div className="nw-heading"><strong>Porty serwera</strong><span className="nw-muted">Schemat wykrytych kart · wybierz port</span></div><div className="nw-ports">{physical.map(i=><button key={i.name} className="nw-port" aria-pressed={selected===i.name} onClick={()=>setSelected(i.name)}><span className="nw-socket" aria-hidden="true"><i className={'nw-led'+(i.carrier?' on':'')}/></span><b>{i.name}</b><small>{netSpeed(i)}</small><small>{netState(i)}</small></button>)}{!physical.length&&<span className="nw-muted">{loaded?'Brak wykrytych portów fizycznych':'Ładowanie portów…'}</span>}</div></div>
  <div className="nw-layout"><div className="nw-panel"><div className="nw-panel-head"><div className="nw-heading"><strong>Interfejsy</strong><span className="nw-muted">{visible.length} widocznych</span></div><input className="nw-search" aria-label="Szukaj interfejsu lub adresu IP" placeholder="Szukaj interfejsu, adresu IP…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="nw-filters">{Object.entries(kinds).map(([k,v])=><button key={k} className={filter===k?'active':''} aria-pressed={filter===k} onClick={()=>setFilter(k)}>{v}</button>)}</div></div>
   {visible.map(i=><button className="nw-row" key={i.name} aria-pressed={selected===i.name} onClick={()=>setSelected(i.name)}><span className="nw-symbol" aria-hidden="true">{i.physical?'↔':'⋈'}</span><span><strong>{i.name} <span className={'nw-status '+i.state}>● {netState(i)}</span></strong><small>{kinds[netKind(i)]} {i.master?'· '+i.master:''}</small><small>{(i.addresses||[]).join(' · ')||'Bez adresu IP'}</small></span><span style={{textAlign:'right'}}><span>{netSpeed(i)}</span><small className="nw-rate">↓ {netRate(last(i,'rx'))}</small><small className="nw-rate">↑ {netRate(last(i,'tx'))}</small></span></button>)}{!visible.length&&<div className="nw-empty">{loaded?'Brak interfejsów spełniających kryteria':'Ładowanie interfejsów…'}</div>}</div>
   <div className="nw-panel">{iface?<><div className="nw-panel-head"><div className="nw-heading"><div><h3 style={{margin:'0 0 5px'}}>{iface.name}</h3><span className="nw-muted">{kinds[netKind(iface)]} · {netState(iface)}</span></div><span className={'nw-status '+iface.state}>●</span></div><div className="nw-filters" style={{marginTop:16}}>{[['overview','Przegląd'],['configuration','Konfiguracja'],['diagnostics','Diagnostyka']].map(([k,v])=><button key={k} className={detail===k?'active':''} onClick={()=>k==='diagnostics'?inspect():setDetail(k)}>{v}</button>)}</div></div><div className="nw-detail-body">
    {detail==='overview'&&<><div className="nw-heading"><div><small className="nw-muted">Odbieranie</small><h3>↓ {netRate(last(iface,'rx'))}</h3></div><div><small className="nw-muted">Wysyłanie</small><h3>↑ {netRate(last(iface,'tx'))}</h3></div></div>{window.NetworkBandwidthChart&&<window.NetworkBandwidthChart iface={selected} series={chart}/>}<p className="nw-muted">Do 60 próbek co około 3 s · MB/s</p>{[['Prędkość połączenia',netSpeed(iface)],['Duplex',iface.duplex||'—'],['MAC',iface.mac||'—'],['MTU',iface.mtu],['Interfejs nadrzędny',iface.master||'—'],['Adresy',(iface.addresses||[]).join(', ')||'Brak']].map(([k,v])=><div className="nw-kv" key={k}><span>{k}</span><b>{v}</b></div>)}</>}
    {detail==='configuration'&&<><button className="btn sm" disabled={busy||!!pending} onClick={()=>onAdvanced(iface)}>DHCP, brama, DNS i VLAN…</button><p className="nw-muted">Zmiany bieżącej konfiguracji. Po potwierdzeniu pozostają do restartu lub ponownego zastosowania konfiguracji przez systemowy menedżer sieci.</p><div className="nw-kv"><span>Stan administracyjny</span><b>{iface.admin_up?'Włączony':'Wyłączony'}</b></div><div className="nw-actions" style={{marginTop:16}}><button className="btn" disabled={busy||!!pending} onClick={()=>mutate({interface:selected,action:iface.admin_up?'down':'up'})}>{iface.admin_up?'Wyłącz interfejs':'Włącz interfejs'}</button><button className="btn" disabled={busy||!!pending} onClick={()=>openEdit('mtu')}>Zmień MTU</button><button className="btn" disabled={busy||!!pending} onClick={()=>openEdit('address')}>Zmień IPv4</button></div>{edit&&<div className="nw-edit"><label>{edit==='mtu'?'MTU (576–9216)':'Adres IPv4 / długość maski'}<input type={edit==='mtu'?'number':'text'} value={value} onChange={e=>setValue(e.target.value)}/></label><p className="nw-muted">Po zastosowaniu masz 90 sekund na potwierdzenie dostępu. Brama, DNS i konfiguracja DHCP pozostają zarządzane przez system.</p><div className="nw-actions"><button className="btn primary" disabled={busy||!!pending} onClick={changeAddress}>Zastosuj na 90 s</button><button className="btn" onClick={()=>setEdit(null)}>Anuluj</button></div></div>}</>}
    {detail==='diagnostics'&&<><div className="nw-heading"><strong>Adresy i liczniki interfejsu</strong><button className="btn sm" disabled={busy} onClick={inspect}>Odśwież</button></div><pre>{busy?'Odczyt…':diagnostic||'Brak danych'}</pre></>}
   </div></>:<div className="nw-empty">Wybierz interfejs</div>}</div>
  </div>
 </div>;
};
window.NetworkWorkspace=NetworkWorkspace;
window.NetworkWorkspaceHelpers={netKind,netRate,netSpeed,netState,networkRequest};

window.networkRequest = networkRequest;
