// Device details use the actual lsblk tree. No generated partitions or SMART values.
const storageRequest=async(url,options={})=>{const r=await fetch(url,{credentials:'include',...options,headers:{'Content-Type':'application/json',...options.headers}});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||`HTTP ${r.status}`);return d;};
const storageHealth=status=>['passed','ok','online'].includes(String(status).toLowerCase())?'ok':['warn','failed','failure','degraded'].includes(String(status).toLowerCase())?'warn':'unknown';
const storageBytes=bytes=>Number.isFinite(Number(bytes))&&bytes!==null?Number(bytes)>=1099511627776?`${(Number(bytes)/1099511627776).toFixed(2)} TiB`:`${(Number(bytes)/1073741824).toFixed(2)} GiB`:'—';
const storageNodes=(node,depth=0)=>node?[{...node,depth},...(node.children||[]).flatMap(child=>storageNodes(child,depth+1))]:[];
const storageCanMount=node=>!!node.fstype&&!node.mountpoint&&!['swap','zfs_member','LVM2_member','linux_raid_member','crypto_LUKS'].includes(node.fstype);
const StorageHealth=({status})=>{const tone=storageHealth(status);return <span className={'badge '+(tone==='unknown'?'':tone)}>{tone==='ok'?'PASSED':tone==='warn'?'UWAGA':'BRAK DANYCH'}</span>;};
const StorageError=({children})=>children?<div className="storage-alert" role="alert">{children}</div>:null;
function StorageDiskDetail({disk,onBack}){
  const [tab,setTab]=React.useState('layout'),[layout,setLayout]=React.useState(null),[error,setError]=React.useState(''),[loading,setLoading]=React.useState(true),[mount,setMount]=React.useState(null),[unmount,setUnmount]=React.useState(null),[fstab,setFstab]=React.useState(false),[mounts,setMounts]=React.useState([]),[busy,setBusy]=React.useState('');
  const alive=React.useRef(true);
  const load=React.useCallback(async()=>{setLoading(true);setError('');const results=await Promise.allSettled([storageRequest('/api/storage/device-layout?device='+encodeURIComponent(disk.bay)),storageRequest('/api/storage/mounts')]);if(!alive.current)return;const [devices,active]=results;if(devices.status==='fulfilled')setLayout(devices.value.blockdevices?.[0]||null);else setError(devices.reason.message);if(active.status==='fulfilled')setMounts(Array.isArray(active.value)?active.value:[]);else setError(active.reason.message);setLoading(false);},[disk.bay]);
  React.useEffect(()=>{alive.current=true;load();window.addEventListener('nimbus-storage-changed',load);return()=>{alive.current=false;window.removeEventListener('nimbus-storage-changed',load);};},[load]);
  const nodes=storageNodes(layout),partitions=nodes.filter(n=>n.type==='part'),mounted=nodes.filter(n=>n.mountpoint);
  const toggle=async(node,record)=>{setBusy(node.path);setError('');try{await storageRequest('/api/storage/fstab',{method:'POST',body:JSON.stringify({device:record.device,target:record.mount,enable:!record.in_fstab})});window.dispatchEvent(new Event('nimbus-storage-changed'));}catch(e){setError(e.message);}finally{setBusy('');}};
  const protectedMount=p=>['/','/boot','/boot/efi','/efi','/usr','/var','/home','/tmp','/opt'].includes(p)||p?.startsWith('/snap/');
  return <div className="storage-detail"><button className="storage-back" onClick={onBack}>← Wszystkie dyski</button><div className="storage-detail-head"><div><div className="storage-eyebrow">MAGAZYN DANYCH / URZĄDZENIE</div><h2>{disk.model==='—'?disk.bay:disk.model}</h2><p className="mono dim">/dev/{disk.bay} · {disk.serial||'Numer seryjny niedostępny'}</p></div><div className="row gap-sm"><StorageHealth status={disk.smart}/><button className="btn" disabled={loading} onClick={load}><window.Icon name="refresh" size={14}/> Odśwież</button></div></div><StorageError>{error}</StorageError><div className="storage-summary"><div><span>Pojemność</span><strong>{layout?storageBytes(layout.size):disk.size}</strong></div><div><span>Partycje</span><strong>{layout?partitions.length:'—'}</strong></div><div><span>Aktywne montowania w drzewie</span><strong>{layout?mounted.length:'—'}</strong></div><div><span>Pula ZFS</span><strong>{disk.pool&&disk.pool!=='—'?disk.pool:'—'}</strong></div></div>
    <div className="tabs"><button className={'tab '+(tab==='layout'?'active':'')} onClick={()=>setTab('layout')}>Partycje i montowania</button><button className={'tab '+(tab==='smart'?'active':'')} onClick={()=>setTab('smart')}>Stan S.M.A.R.T.</button></div>
    {tab==='smart'?<StorageSmartDetails device={disk.bay}/>:<><section className="card"><div className="card-head"><div><div className="card-title">Dysk → partycja → system plików → montowanie</div><div className="card-sub">Bieżący układ urządzeń z lsblk, w tym LVM i RAID</div></div><button className="btn sm" onClick={()=>setFstab(true)}>Edytuj FSTAB</button></div>{loading&&!layout?<div className="storage-empty">Odczytywanie układu dysku…</div>:!layout?<div className="storage-empty">Nie udało się odczytać układu. Ponów odczyt.</div>:<div className="storage-table-wrap"><table className="table"><thead><tr><th>Urządzenie</th><th>Typ / system plików</th><th>Pojemność</th><th>Montowanie</th><th>Po restarcie</th><th>Akcje</th></tr></thead><tbody>{nodes.map((node,i)=>{const record=mounts.find(m=>m.mount===node.mountpoint);const zfs=node.fstype==='zfs_member';return <tr key={node.path+':'+i}><td style={{paddingLeft:16+Math.min(node.depth,4)*16}}><strong className="mono">{node.path||'/dev/'+node.name}</strong><small className="storage-uuid">{node.uuid?'UUID: '+node.uuid:'UUID: —'}</small></td><td><span className="chip">{node.type}</span><div className="storage-cell-note">{node.fstype||'Nie wykryto systemu plików'}</div></td><td className="mono">{storageBytes(node.size)}</td><td className="mono">{node.mountpoint|| (zfs?`Pula ${disk.pool||'ZFS'}`:'Niezamontowane')}{node.ro&&<div className="storage-cell-note">Tylko odczyt</div>}</td><td>{zfs?'Zarządzane przez ZFS':record?<button className={'btn sm '+(record.in_fstab?'primary':'')} disabled={!!busy||protectedMount(node.mountpoint)} onClick={()=>toggle(node,record)}>{busy===node.path?'Zapisywanie…':record.in_fstab?'FSTAB: włączony':'FSTAB: wyłączony'}</button>:'—'}</td><td>{storageCanMount(node)&&<button className="btn sm" onClick={()=>setMount({bay:node.name,device:node.path||'/dev/'+node.name,fs:node.fstype,size:storageBytes(node.size),model:disk.model})}>Zamontuj</button>}{record&&!protectedMount(node.mountpoint)&&!zfs&&<button className="btn sm" onClick={()=>setUnmount({mp:record.mount,device:record.device,fs:record.fs,inFstab:record.in_fstab,type:record.fs})}>Odmontuj</button>}</td></tr>;})}</tbody></table></div>}</section><p className="storage-note">Urządzenia bez partycji mogą mieć system plików bezpośrednio na całym dysku. Wolnego miejsca do utworzenia partycji nie wyliczamy z rozmiarów LVM ani RAID.</p></>}
    {mount&&<window.StorageMountDialog disk={mount} onClose={()=>setMount(null)}/>}{unmount&&<window.StorageUnmountDialog mount={unmount} onClose={()=>setUnmount(null)}/>}{fstab&&<window.StorageFstabDialog onClose={()=>setFstab(false)}/>}
  </div>;
}
function StorageSmartDetails({device}){
  const [data,setData]=React.useState(null),[error,setError]=React.useState(''),[loading,setLoading]=React.useState(true),[busy,setBusy]=React.useState(false),[message,setMessage]=React.useState('');
  const load=React.useCallback(async()=>{setLoading(true);setError('');try{setData(await storageRequest('/api/storage/smart/details/'+encodeURIComponent(device)));}catch(e){setError(e.message);}finally{setLoading(false);}},[device]);
  React.useEffect(()=>{load();},[load]);
  const source=data?.nimbus_source==='ssacli'?'HP Smart Array (stan kontrolera)':'smartctl';const status=data?.smart_status?.passed===true?'passed':data?.smart_status?.passed===false?'warn':'unknown';
  const rows=data?.ata_smart_attributes?.table||[];const health=data?.nvme_smart_health_information_log;const errors=data?.scsi_error_counter_log;
  const run=async type=>{setBusy(true);setError('');setMessage('');try{const d=await storageRequest('/api/storage/smart/run-test',{method:'POST',body:JSON.stringify({device,type})});setMessage(d.output||'smartctl potwierdził uruchomienie testu.');}catch(e){setError(e.message);}finally{setBusy(false);}};
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`smart-${device}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <div className="storage-detail"><StorageError>{error}</StorageError><section className="card"><div className="card-head"><div><div className="card-title">Stan dysku</div><div className="card-sub">{data?source:'Odczyt na żądanie'} · /dev/{device}</div></div><div className="row gap-sm"><button className="btn sm" disabled={loading} onClick={load}>{loading?'Odczytywanie…':'Odśwież SMART'}</button><button className="btn sm" disabled={!data} onClick={download}>Pobierz JSON</button></div></div>{data?<div className="card-body"><div className="storage-summary"><div><span>Ocena urządzenia</span><StorageHealth status={status}/></div><div><span>Temperatura</span><strong>{data.temperature?.current!==undefined?data.temperature.current+'°C':health?.temperature!==undefined?health.temperature+'°C':'—'}</strong></div><div><span>Godziny pracy</span><strong>{data.power_on_time?.hours??health?.power_on_hours??'—'}</strong></div><div><span>Protokół</span><strong>{data.device?.protocol||'—'}</strong></div></div>{data.nimbus_source==='ssacli'?<p className="storage-note">Kontroler udostępnia stan dysku. Nie udostępnia tutaj atrybutów ATA ani uruchamiania testów smartctl.</p>:<div className="storage-smart-actions"><button className="btn" disabled={busy} onClick={()=>run('short')}>Test krótki</button><button className="btn" disabled={busy} onClick={()=>run('long')}>Test rozszerzony</button><small className="dim">Wynik testu sprawdzisz po odświeżeniu raportu. Test rozszerzony może trwać wiele godzin.</small></div>}</div>:<div className="storage-empty">{loading?'Pobieranie danych z urządzenia…':'Brak potwierdzonego odczytu SMART. Szczegóły błędu są powyżej.'}</div>}</section>
    {message&&<pre className="storage-output" role="status">{message}</pre>}
    {rows.length>0&&<section className="card"><div className="card-head"><div className="card-title">Atrybuty ATA</div></div><div className="storage-table-wrap"><table className="table"><thead><tr><th>ID</th><th>Atrybut</th><th>Wartość</th><th>Próg</th><th>RAW</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.id}</td><td>{a.name}</td><td>{a.value??'—'}</td><td>{a.thresh??'—'}</td><td className="mono">{a.raw?.string??a.raw?.value??'—'}</td></tr>)}</tbody></table></div></section>}
    {health&&<section className="card"><div className="card-head"><div className="card-title">NVMe — zdrowie nośnika</div></div><div className="card-body"><dl className="storage-facts">{[['Zużycie',health.percentage_used===undefined?'—':health.percentage_used+'%'],['Błędy nośnika',health.media_errors??'—'],['Zapas dostępny',health.available_spare===undefined?'—':health.available_spare+'%'],['Ostrzeżenia krytyczne',health.critical_warning??'—']].map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v}</dd></React.Fragment>)}</dl></div></section>}
    {errors&&<section className="card"><div className="card-head"><div className="card-title">SAS / SCSI — liczniki błędów</div></div><div className="card-body"><p>Defekty narastające: <strong>{data.scsi_grown_defect_list??'—'}</strong></p><pre className="storage-output">{JSON.stringify(errors,null,2)}</pre></div></section>}
    {data?.ata_smart_self_test_log&&<section className="card"><div className="card-head"><div className="card-title">Historia testów</div></div><div className="card-body"><pre className="storage-output">{JSON.stringify(data.ata_smart_self_test_log,null,2)}</pre></div></section>}
  </div>;
}
window.StorageDiskDetail=StorageDiskDetail;window.StorageHealth=StorageHealth;window.StorageSmartDetails=StorageSmartDetails;
