const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),esbuild=require('esbuild');
const compiled=esbuild.transformSync(fs.readFileSync('web/static/screens-kvm-workspace.jsx','utf8'),{loader:'jsx',target:'es2020'}).code;
function load(fetch,states={}){let hook=0;const ctx={fetch,Set,window:{KVMPanels:{}},React:{createElement:(type,props,...children)=>({type,props:{...props,children}}),useState:v=>[Object.hasOwn(states,hook)?states[hook++]:((hook++),v),()=>{}],useRef:v=>({current:v}),useCallback:f=>f,useEffect:()=>{}}};vm.createContext(ctx);vm.runInContext(compiled+'\nglobalThis.ui={kvmRequest,kvmFilter,kvmState,kvmActions,KVMWorkspace,KVMSnapshots};',ctx);return ctx.ui;}
test('KVM rejects HTTP errors and legacy success envelopes containing errors',async()=>{for(const ok of [true,false])await assert.rejects(()=>load(async()=>({ok,status:502,json:async()=>({error:'libvirt niedostępny'})})).kvmRequest('vms'),/libvirt niedostępny/);});
test('KVM reports a non-JSON gateway response',async()=>{await assert.rejects(()=>load(async()=>({ok:false,status:502,json:async()=>{throw Error();}})).kvmRequest('vms'),/HTTP 502/);});
test('paused machines resume; unknown and shutting down states do not offer start',()=>{const ui=load();assert.equal(ui.kvmActions('paused')[0][0],'resume');assert.equal(ui.kvmActions('unknown').length,0);assert.equal(ui.kvmActions('shutting_down').length,0);assert.equal(ui.kvmState('unknown')[0],'Stan nieznany');});
test('search matches secondary IP and respects state selection',()=>{const ui=load(),vms=[{name:'Debian',state:'paused',ips:['10.0.0.2','10.1.0.3']},{name:'Windows',state:'running'}];assert.equal(ui.kvmFilter(vms,'10.1.0.3','paused')[0].name,'Debian');assert.equal(ui.kvmFilter(vms,'DEBIAN','running').length,0);});
test('workspace initial render and snapshot loading render have no missing variables',()=>{const ui=load();assert.ok(ui.KVMWorkspace());assert.ok(ui.KVMSnapshots({vm:{id:'debian'},onChange:()=>{}}));});
test('snapshot creation calls libvirt API instead of inventing a local entry',async()=>{let request;const ui=load(async(url,opts)=>{request={url,opts};return {ok:true,status:200,json:async()=>({status:'ok'})};});await ui.kvmRequest('snapshots?vm=debian',{name:'before-update',desc:'Test'});assert.equal(request.url,'/api/kvm/snapshots?vm=debian');assert.equal(request.opts.method,'POST');assert.equal(JSON.parse(request.opts.body).name,'before-update');});

test('populated grid, list and machine details render with server data',()=>{const machine={id:'debian',name:'Debian',state:'paused',cpu:2,ram:2048,ips:['10.0.0.2']};for(const overrides of [{},{10:'list'},{11:'debian'},{11:'debian',12:'snapshots'}]){const ui=load(null,{0:[machine],1:{installed:true,running:true},2:false,6:new Date(),...overrides});assert.ok(ui.KVMWorkspace());}});
test('snapshot form submits and reloads the backend list',async()=>{const calls=[];const ui=load(async(url,opts)=>{calls.push({url,opts});return {ok:true,status:200,json:async()=>opts.method==='POST'?{status:'ok'}:{snapshots:[]}};});const tree=ui.KVMSnapshots({vm:{id:'debian'},onChange:()=>{}});const form=tree.props.children.find(child=>child&&child.type==='form');await form.props.onSubmit({preventDefault:()=>{}});assert.equal(calls.length,2);assert.equal(calls[0].opts.method,'POST');assert.equal(calls[1].opts.method,'GET');});
