const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),esbuild=require('esbuild');
const compiled=esbuild.transformSync(fs.readFileSync('web/static/screens-network-workspace.jsx','utf8'),{loader:'jsx'}).code;
function load(fetch,states={}){let hook=0;const ctx={fetch,window:{},Date,React:{createElement:(type,props,...children)=>({type,props:{...props,children}}),useState:v=>[Object.hasOwn(states,hook)?states[hook++]:((hook++),v),()=>{}],useCallback:f=>f,useEffect:()=>{}}};vm.createContext(ctx);vm.runInContext(compiled,ctx);return ctx.window;}
function nodes(tree){return !tree||typeof tree!=='object'?[]:[tree,...(tree.props?.children||[]).flat(Infinity).flatMap(nodes)]}
const iface={name:'enp2s0',kind:'physical',physical:true,admin_up:true,carrier:false,state:'no-carrier',speed_mbps:1000,mtu:9000,addresses:['10.0.0.2/20']};
test('no carrier preserves enabled state without claiming negotiated speed',()=>{const h=load().NetworkWorkspaceHelpers;assert.equal(h.netState(iface),'Brak linku');assert.equal(h.netSpeed(iface),'Brak linku');assert.equal(h.netSpeed({...iface,carrier:true,speed_mbps:2500}),'2.5 Gb/s')});
test('missing rates and unsupported speeds do not become zeros',()=>{const h=load().NetworkWorkspaceHelpers;assert.equal(h.netRate(null),'—');assert.equal(h.netRate(0),'0.0 kB/s');assert.equal(h.netSpeed({speed_mbps:-1}),'—')});
test('HTTP and legacy API failures are surfaced',async()=>{for(const ok of [true,false])await assert.rejects(()=>load(async()=>({ok,json:async()=>({error:'brak uprawnień'})})).NetworkWorkspaceHelpers.networkRequest('/x'),/brak uprawnień/);await assert.rejects(()=>load(async()=>({ok:false,status:502,json:async()=>{throw Error()}})).NetworkWorkspaceHelpers.networkRequest('/x'),/HTTP 502/)});
test('empty, populated, configuration, diagnostics and pending views render',()=>{for(const state of [{},{0:[iface],1:iface.name},{0:[iface],1:iface.name,10:'configuration'},{0:[iface],1:iface.name,10:'diagnostics'},{8:{id:'abc',interface:iface.name,deadline:new Date(Date.now()+90000).toISOString()}}])assert.ok(load(null,state).NetworkWorkspace({onAdvanced:()=>{}}))});
test('enabling no-carrier interface does not issue down as a guessed toggle',()=>{const tree=load(null,{0:[iface],1:iface.name,10:'configuration'}).NetworkWorkspace({onAdvanced:()=>{}});assert.ok(nodes(tree).some(n=>n.type==='button'&&n.props.children.includes('Wyłącz interfejs')))});
test('physical totals exclude traffic already counted on bridge',()=>{const bridge={...iface,name:'br0',physical:false,kind:'bridge'},tree=load(null,{0:[iface,bridge],1:iface.name,4:{enp2s0:{rx:[2],tx:[1]},br0:{rx:[2],tx:[1]}},6:true}).NetworkWorkspace({onAdvanced:()=>{}});const strong=nodes(tree).filter(n=>n.type==='strong').map(n=>n.props.children[0]);assert.ok(strong.includes('2.00 MB/s'));assert.ok(!strong.includes('4.00 MB/s'))});
