const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),esbuild=require('esbuild');
const code=esbuild.transformSync(fs.readFileSync('web/static/screens-storage-workspace.jsx','utf8'),{loader:'jsx'}).code;
const disks=[{bay:'sda',serial:'A',model:'SAS',size:'1 TB',smart:'passed'},{bay:'sdb',serial:'B',model:'SAS',size:'1 TB',smart:'unknown'}];
function load(states={}){let hook=0;const ctx={window:{useStore:()=>disks,Icon:()=>null,StoragePartitionPlan:()=>null},React:{createElement:(type,props,...children)=>({type,props:{...props,children}}),useState:v=>[Object.hasOwn(states,hook)?states[hook++]:((hook++),v),()=>{}],useCallback:f=>f,useEffect:()=>{}}};vm.createContext(ctx);vm.runInContext(code+';globalThis.ui={StorageWorkspace,StorageInspector,swDiskForSlot,swTone};',ctx);return ctx.ui;}
const walk=t=>!t||typeof t!=='object'?[]:[t,...(t.props?.children||[]).flat(Infinity).flatMap(walk)];
test('bay identity matches device or unique serial and rejects conflicting identity',()=>{const h=load();assert.equal(h.swDiskForSlot({device:'/dev/sdb',serial:'B'},disks).bay,'sdb');assert.equal(h.swDiskForSlot({serial:'A'},disks).bay,'sda');assert.equal(h.swDiskForSlot({device:'/dev/sda',serial:'OTHER'},disks),null);assert.equal(h.swDiskForSlot({slot:2},disks),null)});
test('unknown status is never healthy',()=>{assert.equal(load().swTone(undefined),'unknown');assert.equal(load().swTone('ONLINE'),'ok')});
test('controller map selects actual disk and opens selected inspector',()=>{let chosen;const ui=load({2:{slots:[{slot:2,pd_id:'1I:1:2',device:'/dev/sdb',serial:'B',occupied:true}],enclosure:{total_slots:25}}});const tree=ui.StorageWorkspace({selected:'sdb',onDisk:d=>chosen=d,onNavigate:()=>{}});const bays=walk(tree).filter(n=>n.type==='button'&&n.props['aria-label']?.startsWith('Zatoka '));assert.equal(bays.length,25);assert.equal(bays[1].props['aria-pressed'],true);bays[1].props.onClick();assert.equal(chosen.bay,'sdb');assert.notEqual(bays[0].props.disabled,true)});
test('unmapped bays are selectable without inventing a device',()=>{let selections=0;const tree=load({2:{tool:'ssacli',slots:[{slot:1,device:'/dev/sda',occupied:true}]}}).StorageWorkspace({onNavigate:()=>{},onDisk:()=>selections++});const bays=walk(tree).filter(n=>n.props['aria-label']?.startsWith('Zatoka '));assert.ok(bays.every(n=>!n.props.disabled));bays[0].props.onClick();assert.equal(selections,0)});
test('selected unmatched bay shows its own controller details rather than first disk',()=>{const slot={slot:3,pd_id:'1I:1:3',serial:'UNMAPPED',model:'SAS drive',occupied:true};const tree=load({2:{slots:[slot]},8:3}).StorageWorkspace({onNavigate:()=>{}});const inspector=walk(tree).find(n=>typeof n.type==='function'&&n.type.name==='StorageBayInspector');assert.ok(inspector);assert.equal(inspector.props.number,3);assert.equal(inspector.props.slot.serial,'UNMAPPED');assert.ok(inspector.type(inspector.props))});
test('empty and populated inspector render without fabricated partitions',()=>{assert.ok(load().StorageInspector({disk:null}));const tree=load({0:{name:'sda',size:1000000000,fstype:'ext4'}}).StorageInspector({disk:disks[0],onFull:()=>{},onFormat:()=>{}});assert.ok(tree);assert.equal(walk(tree).filter(n=>n.props.className==='sw-partition').length,1)});
